// --- DATA STRUCTURE: Minna No Nihongo Vocabulary ---
const minnaNoNihongoData = {
    "Lesson 1": [
        { question: "I, Me", options: ["わたし", "あなた", "あのひと", "だれ"], correctIndex: 0, explanation: "わたし means I or me." },
        { question: "We", options: ["わたし", "あなた", "わたしたち", "みなさん"], correctIndex: 2, explanation: "わたしたち means we." },
        { question: "You", options: ["わたし", "あなた", "あのひと", "みなさん"], correctIndex: 1, explanation: "あなた means you." },
        { question: "That person, he, she", options: ["だれ", "どなた", "あなた", "あのひと"], correctIndex: 3, explanation: "あのひと means that person (he/she)." },
        { question: "That person, he, she (polite equivalent)", options: ["あのかた", "あのひと", "あなた", "みなさん"], correctIndex: 0, explanation: "あのかた is the polite equivalent of あのひと." },
        { question: "Ladies and gentlemen, all of you", options: ["みなさん", "わたしたち", "あのひと", "あなた"], correctIndex: 0, explanation: "みなさん means everyone or all of you." },
        { question: "Mr., Ms. (title of respect)", options: ["〜ちゃん", "〜じん", "〜さん", "〜さい"], correctIndex: 2, explanation: "〜さん is a title of respect added to a name." },
        { question: "Suffix often added to a child's name", options: ["〜さん", "〜ちゃん", "〜じん", "〜さい"], correctIndex: 1, explanation: "〜ちゃん is used affectionately for children." },
        { question: "Suffix meaning a national of a country", options: ["〜さん", "〜ちゃん", "〜じん", "〜さい"], correctIndex: 2, explanation: "〜じん indicates nationality (e.g., アメリカじん)." },
        { question: "Teacher, Instructor", options: ["がくせい", "せんせい", "いしゃ", "きょうし"], correctIndex: 1, explanation: "せんせい means teacher." },
        { question: "Teacher, Instructor (referring to one's own profession)", options: ["がくせい", "せんせい", "いしゃ", "きょうし"], correctIndex: 3, explanation: "きょうし is used when talking about your own job as a teacher." },
        { question: "Student", options: ["せんせい", "ぎんこういん", "がくせい", "エンジニア"], correctIndex: 2, explanation: "がくせい means student." },
        { question: "Company employee", options: ["かいしゃいん", "しゃいん", "いしゃ", "けんきゅうしゃ"], correctIndex: 0, explanation: "かいしゃいん means company employee." },
        { question: "Employee of ~ company", options: ["かいしゃいん", "しゃいん", "ぎんこういん", "せんせい"], correctIndex: 1, explanation: "しゃいん is used with a company name (e.g., IMCのしゃいん)." },
        { question: "Bank employee", options: ["いしゃ", "ぎんこういん", "かいしゃいん", "せんせい"], correctIndex: 1, explanation: "ぎんこういん means bank employee." },
        { question: "Medical doctor", options: ["エンジニア", "けんきゅうしゃ", "がくせい", "いしゃ"], correctIndex: 3, explanation: "いしゃ means medical doctor." },
        { question: "Researcher, scholar", options: ["けんきゅうしゃ", "いしゃ", "せんせい", "しゃいん"], correctIndex: 0, explanation: "けんきゅうしゃ means researcher." },
        { question: "Engineer", options: ["エンジニア", "いしゃ", "ぎんこういん", "がくせい"], correctIndex: 0, explanation: "エンジニア is the katakana word for engineer." },
        { question: "University", options: ["びょういん", "だいがく", "ぎんこう", "かいしゃ"], correctIndex: 1, explanation: "だいがく means university." },
        { question: "Hospital", options: ["だいがく", "びょういん", "ぎんこう", "かいしゃ"], correctIndex: 1, explanation: "びょういん means hospital." },
        { question: "Electricity, light", options: ["だいがく", "びょういん", "でんき", "かいしゃ"], correctIndex: 2, explanation: "でんき means electricity or light." },
        { question: "Who", options: ["だれ", "なに", "どこ", "いつ"], correctIndex: 0, explanation: "だれ means who." },
        { question: "Who (polite equivalent)", options: ["どなた", "だれ", "なに", "どこ"], correctIndex: 0, explanation: "どなた is the polite equivalent of だれ." },
        { question: "—years old", options: ["〜さん", "〜ちゃん", "〜じん", "〜さい"], correctIndex: 3, explanation: "〜さい is the counter for age." },
        { question: "How old", options: ["だれ", "どなた", "なんさい", "いつ"], correctIndex: 2, explanation: "なんさい means how old." },
        { question: "How old (polite equivalent)", options: ["なんさい", "おいくつ", "だれ", "どなた"], correctIndex: 1, explanation: "おいくつ is the polite equivalent of なんさい." },
        { question: "Yes", options: ["いいえ", "はい", "そう", "ちがいます"], correctIndex: 1, explanation: "はい means yes." },
        { question: "No", options: ["はい", "いいえ", "そう", "ちがいます"], correctIndex: 1, explanation: "いいえ means no." },
        { question: "How do you do? (meeting for the first time)", options: ["どうぞよろしく", "はじめまして", "しつれいですが", "おなまえは？"], correctIndex: 1, explanation: "はじめまして is used when meeting someone for the first time." },
        { question: "I'm from ~ (country)", options: ["〜からきました", "〜じん", "〜さん", "〜さい"], correctIndex: 0, explanation: "〜からきました means 'I came from...' or 'I am from...'." },
        { question: "Pleased to meet you", options: ["はじめまして", "どうぞよろしく", "しつれいですが", "おなまえは？"], correctIndex: 1, explanation: "どうぞよろしく (or どうぞよろしくおねがいします) means pleased to meet you." },
        { question: "Excuse me, but", options: ["はじめまして", "どうぞよろしく", "しつれいですが", "おなまえは？"], correctIndex: 2, explanation: "しつれいですが is used when asking for personal information like a name." },
        { question: "May I have your name?", options: ["はじめまして", "どうぞよろしく", "しつれいですが", "おなまえは？"], correctIndex: 3, explanation: "おなまえは？ means 'What is your name?'." },
        { question: "This is Mr./Ms. ~", options: ["こちらは〜さんです", "〜からきました", "どうぞよろしく", "はじめまして"], correctIndex: 0, explanation: "こちらは〜さんです is used when introducing someone else." }
    ],
    "Lesson 2": [
        { question: "This (thing here)", options: ["それ", "あれ", "これ", "どれ"], correctIndex: 2, explanation: "これ refers to a thing near the speaker." },
        { question: "That (thing near the listener)", options: ["これ", "それ", "あれ", "どれ"], correctIndex: 1, explanation: "それ refers to a thing near the listener." },
        { question: "That (thing over there)", options: ["これ", "それ", "あれ", "どれ"], correctIndex: 2, explanation: "あれ refers to a thing far from both speaker and listener." },
        { question: "Which one", options: ["これ", "それ", "あれ", "どれ"], correctIndex: 3, explanation: "どれ means which one." },
        { question: "This ~ (noun)", options: ["この", "その", "あの", "どの"], correctIndex: 0, explanation: "この must be followed by a noun (e.g., この ほん)." },
        { question: "That ~ (noun) near the listener", options: ["この", "その", "あの", "どの"], correctIndex: 1, explanation: "その must be followed by a noun." },
        { question: "That ~ (noun) over there", options: ["この", "その", "あの", "どの"], correctIndex: 2, explanation: "あの must be followed by a noun." },
        { question: "Which ~ (noun)", options: ["この", "その", "あの", "どの"], correctIndex: 3, explanation: "どの must be followed by a noun." },
        { question: "Book", options: ["じしょ", "ほん", "ざっし", "しんぶん"], correctIndex: 1, explanation: "ほん means book." },
        { question: "Dictionary", options: ["ほん", "ざっし", "じしょ", "てちょう"], correctIndex: 2, explanation: "じしょ means dictionary." },
        { question: "Magazine", options: ["しんぶん", "ざっし", "ノート", "ほん"], correctIndex: 1, explanation: "ざっし means magazine." },
        { question: "Newspaper", options: ["しんぶん", "ざっし", "てちょう", "じしょ"], correctIndex: 0, explanation: "しんぶん means newspaper." },
        { question: "Notebook", options: ["てちょう", "ノート", "めいし", "カード"], correctIndex: 1, explanation: "ノート is a katakana word for notebook." },
        { question: "Pocket notebook", options: ["ノート", "ほん", "てちょう", "めいし"], correctIndex: 2, explanation: "てちょう means a small pocket notebook." },
        { question: "Business card", options: ["カード", "めいし", "えんぴつ", "かぎ"], correctIndex: 1, explanation: "めいし means business card." },
        { question: "Card", options: ["カード", "めいし", "てちょう", "ノート"], correctIndex: 0, explanation: "カード means card (like a credit card or key card)." },
        { question: "Telephone card", options: ["カード", "テレホンカード", "めいし", "ノート"], correctIndex: 1, explanation: "テレホンカード means telephone card." },
        { question: "Pencil", options: ["ボールペン", "シャープペンシル", "えんぴつ", "かさ"], correctIndex: 2, explanation: "えんぴつ means pencil." },
        { question: "Ballpoint pen", options: ["ボールペン", "シャープペンシル", "えんぴつ", "かぎ"], correctIndex: 0, explanation: "ボールペン is a katakana word for ballpoint pen." },
        { question: "Mechanical pencil", options: ["ボールペン", "シャープペンシル", "えんぴつ", "ノート"], correctIndex: 1, explanation: "シャープペンシル is a mechanical pencil." },
        { question: "Key", options: ["かぎ", "とけい", "かさ", "かばん"], correctIndex: 0, explanation: "かぎ means key." },
        { question: "Watch, clock", options: ["とけい", "かぎ", "かさ", "くつ"], correctIndex: 0, explanation: "とけい means watch or clock." },
        { question: "Umbrella", options: ["かぎ", "とけい", "かさ", "かばん"], correctIndex: 2, explanation: "かさ means umbrella." },
        { question: "Bag, briefcase", options: ["かさ", "かばん", "つくえ", "いす"], correctIndex: 1, explanation: "かばん means bag or briefcase." },
        { question: "Cassette tape", options: ["テープ", "ラジオ", "テレビ", "カメラ"], correctIndex: 0, explanation: "テープ means tape or cassette tape." },
        { question: "CD, Compact Disc", options: ["テープ", "CD", "テレビ", "カメラ"], correctIndex: 1, explanation: "CD means compact disc." },
        { question: "Television", options: ["ラジオ", "カメラ", "テレビ", "コンピューター"], correctIndex: 2, explanation: "テレビ means television." },
        { question: "Radio", options: ["ラジオ", "カメラ", "テレビ", "コンピューター"], correctIndex: 0, explanation: "ラジオ means radio." },
        { question: "Camera", options: ["ラジオ", "カメラ", "テレビ", "コンピューター"], correctIndex: 1, explanation: "カメラ means camera." },
        { question: "Computer", options: ["ラジオ", "カメラ", "テレビ", "コンピューター"], correctIndex: 3, explanation: "コンピューター means computer." },
        { question: "Automobile, car", options: ["じどうしゃ", "テレビ", "ラジオ", "カメラ"], correctIndex: 0, explanation: "じどうしゃ means car. くるま is also commonly used." },
        { question: "Desk", options: ["いす", "つくえ", "テレビ", "カメラ"], correctIndex: 1, explanation: "つくえ means desk." },
        { question: "Chair", options: ["つくえ", "いす", "かばん", "かさ"], correctIndex: 1, explanation: "いす means chair." },
        { question: "Chocolate", options: ["チョコレート", "コーヒー", "テレビ", "ラジオ"], correctIndex: 0, explanation: "チョコレート means chocolate." },
        { question: "Coffee", options: ["チョコレート", "コーヒー", "ノート", "カメラ"], correctIndex: 1, explanation: "コーヒー means coffee." },
        { question: "English language", options: ["えいご", "にほんご", "〜ご", "なん"], correctIndex: 0, explanation: "えいご means the English language." },
        { question: "Japanese language", options: ["えいご", "にほんご", "〜ご", "なん"], correctIndex: 1, explanation: "にほんご means the Japanese language." },
        { question: "〜 language", options: ["えいご", "にほんご", "〜ご", "なん"], correctIndex: 2, explanation: "〜ご is the suffix for languages (e.g., フランスご)." },
        { question: "What", options: ["だれ", "どこ", "いつ", "なん"], correctIndex: 3, explanation: "なん (or なに) means what." },
        { question: "Yes, it is. / That's right.", options: ["そうです", "ちがいます", "そうですか", "どうぞ"], correctIndex: 0, explanation: "そうです is used to agree or confirm." },
        { question: "No, it isn't. / You are wrong.", options: ["そうです", "ちがいます", "そうですか", "どうぞ"], correctIndex: 1, explanation: "ちがいます literally means 'it is different' but is used to say 'no, that's incorrect'." },
        { question: "I see. / Is that so?", options: ["そうです", "ちがいます", "そうですか", "どうぞ"], correctIndex: 2, explanation: "そうですか is used to show you understand new information." },
        { question: "Well... (hesitation)", options: ["あのう", "どうぞ", "どうも", "そうです"], correctIndex: 0, explanation: "あのう is a filler word used when hesitating or getting someone's attention politely." },
        { question: "It's nothing. / It's a token of my gratitude.", options: ["ほんのきもちです", "どうぞ", "どうも", "そうですか"], correctIndex: 0, explanation: "ほんのきもちです is often said when giving a small gift." },
        { question: "Please. / Here you are.", options: ["どうぞ", "どうも", "あのう", "そうです"], correctIndex: 0, explanation: "どうぞ is used when offering something to someone." },
        { question: "Well / Thanks", options: ["どうも", "どうぞ", "あのう", "そうです"], correctIndex: 0, explanation: "どうも is a casual way to say thanks, or used to emphasize a greeting." },
        { question: "Thank you very much.", options: ["どうぞよろしく", "どうもありがとうございます", "そうですか", "ちがいます"], correctIndex: 1, explanation: "どうもありがとうございます is the standard polite way to say thank you." },
        { question: "I hope for your kind assistance from now on.", options: ["こちらこそよろしく", "これからおせわになります", "ほんのきもちです", "そうですか"], correctIndex: 1, explanation: "これからおせわになります is a formal greeting used when starting a new relationship." },
        { question: "I am pleased to meet you too. / The pleasure is mine.", options: ["これからおせわになります", "こちらこそよろしく", "ほんのきもちです", "どうも"], correctIndex: 1, explanation: "こちらこそよろしく is the polite reply to どうぞよろしく." }
    ],
    "Lesson 3": [
        { question: "Here, this place", options: ["そこ", "あそこ", "ここ", "どこ"], correctIndex: 2, explanation: "ここ means here." },
        { question: "There, that place near you", options: ["ここ", "そこ", "あそこ", "どこ"], correctIndex: 1, explanation: "そこ means there." },
        { question: "That place over there", options: ["ここ", "そこ", "あそこ", "どこ"], correctIndex: 2, explanation: "あそこ means over there." },
        { question: "Where, what place", options: ["ここ", "そこ", "あそこ", "どこ"], correctIndex: 3, explanation: "どこ means where." },
        { question: "This way, this place (polite equivalent of ここ)", options: ["そちら", "こちら", "あちら", "どちら"], correctIndex: 1, explanation: "こちら is the polite form of ここ." },
        { question: "That way, that place (polite equivalent of そこ)", options: ["こちら", "そちら", "あちら", "どちら"], correctIndex: 1, explanation: "そちら is the polite form of そこ." },
        { question: "That way, that place over there (polite equivalent of あそこ)", options: ["こちら", "そちら", "あちら", "どちら"], correctIndex: 2, explanation: "あちら is the polite form of あそこ." },
        { question: "Which way, where (polite equivalent of どこ)", options: ["こちら", "そちら", "あちら", "どちら"], correctIndex: 3, explanation: "どちら is the polite form of どこ." },
        { question: "Classroom", options: ["しょくどう", "きょうしつ", "じむしょ", "へや"], correctIndex: 1, explanation: "きょうしつ means classroom." },
        { question: "Dining hall, canteen", options: ["きょうしつ", "じむしょ", "しょくどう", "かいぎしつ"], correctIndex: 2, explanation: "しょくどう means dining hall or canteen." },
        { question: "Office", options: ["じむしょ", "きょうしつ", "しょくどう", "うけつけ"], correctIndex: 0, explanation: "じむしょ means office." },
        { question: "Conference room, assembly room", options: ["しょくどう", "じむしょ", "かいぎしつ", "ロビー"], correctIndex: 2, explanation: "かいぎしつ means conference room." },
        { question: "Reception desk", options: ["うけつけ", "ロビー", "へや", "トイレ"], correctIndex: 0, explanation: "うけつけ means reception desk." },
        { question: "Lobby", options: ["うけつけ", "ロビー", "へや", "かいだん"], correctIndex: 1, explanation: "ロビー is a katakana word for lobby." },
        { question: "Room", options: ["へや", "トイレ", "かいだん", "うち"], correctIndex: 0, explanation: "へや means room." },
        { question: "Toilet, restroom", options: ["へや", "おてあらい", "かいだん", "エレベーター"], correctIndex: 1, explanation: "おてあらい (or トイレ) means restroom/toilet." },
        { question: "Staircase", options: ["トイレ", "エレベーター", "かいだん", "エスカレーター"], correctIndex: 2, explanation: "かいだん means staircase or stairs." },
        { question: "Elevator, lift", options: ["かいだん", "エスカレーター", "エレベーター", "うち"], correctIndex: 2, explanation: "エレベーター is elevator." },
        { question: "Escalator", options: ["かいだん", "エレベーター", "エスカレーター", "へや"], correctIndex: 2, explanation: "エスカレーター is escalator." },
        { question: "Country", options: ["かいしゃ", "うち", "くに", "でんわ"], correctIndex: 2, explanation: "くに (or おくに) means country." },
        { question: "Company", options: ["くに", "かいしゃ", "うち", "くつ"], correctIndex: 1, explanation: "かいしゃ means company." },
        { question: "House, home", options: ["うち", "くに", "かいしゃ", "でんわ"], correctIndex: 0, explanation: "うち means house or home." },
        { question: "Telephone, telephone call", options: ["くつ", "でんわ", "ネクタイ", "ワイン"], correctIndex: 1, explanation: "でんわ means telephone." },
        { question: "Shoes", options: ["ネクタイ", "ワイン", "くつ", "たばこ"], correctIndex: 2, explanation: "くつ means shoes." },
        { question: "Necktie", options: ["くつ", "ネクタイ", "ワイン", "うりば"], correctIndex: 1, explanation: "ネクタイ means necktie." },
        { question: "Wine", options: ["ネクタイ", "ワイン", "たばこ", "ちか"], correctIndex: 1, explanation: "ワイン means wine." },
        { question: "Tobacco, cigarette", options: ["ワイン", "たばこ", "うりば", "ちか"], correctIndex: 1, explanation: "たばこ means tobacco or cigarette." },
        { question: "Department, counter (in a department store)", options: ["ちか", "うりば", "かい", "えん"], correctIndex: 1, explanation: "うりば means selling area or counter." },
        { question: "Basement", options: ["ちか", "うりば", "かい", "えん"], correctIndex: 0, explanation: "ちか means basement or underground." },
        { question: "—th floor", options: ["〜えん", "〜かい", "〜がい", "〜かい / 〜がい"], correctIndex: 3, explanation: "〜かい (or 〜がい for 3rd floor/sangai) is the counter for floors." },
        { question: "What floor", options: ["いくら", "なんがい", "ひゃく", "せん"], correctIndex: 1, explanation: "なんがい means what floor." },
        { question: "—yen", options: ["〜かい", "〜えん", "いくら", "まん"], correctIndex: 1, explanation: "〜えん is the counter for Japanese yen." },
        { question: "How much", options: ["なんがい", "いくら", "ひゃく", "せん"], correctIndex: 1, explanation: "いくら means how much (price)." },
        { question: "Hundred", options: ["ひゃく", "せん", "まん", "えん"], correctIndex: 0, explanation: "ひゃく means one hundred." },
        { question: "Thousand", options: ["ひゃく", "せん", "まん", "いくら"], correctIndex: 1, explanation: "せん means one thousand." },
        { question: "Ten thousand", options: ["ひゃく", "せん", "まん", "えん"], correctIndex: 2, explanation: "まん means ten thousand." },
        { question: "Excuse me", options: ["じゃ", "すみません", "ください", "でございます"], correctIndex: 1, explanation: "すみません is used to apologize or get someone's attention." },
        { question: "Polite equivalent of です", options: ["すみません", "〜でございます", "〜をみせてください", "じゃ"], correctIndex: 1, explanation: "〜でございます is a very polite way to say 'is/are'." },
        { question: "Please show me ~", options: ["じゃ", "〜をみせてください", "〜をください", "すみません"], correctIndex: 1, explanation: "〜をみせてください is used when asking a shop clerk to show you an item." },
        { question: "Well, then, in that case", options: ["じゃ", "すみません", "〜でございます", "どうぞ"], correctIndex: 0, explanation: "じゃ is a conversational way to say 'well then'." },
        { question: "Give me ~, please", options: ["〜をみせてください", "〜をください", "じゃ", "すみません"], correctIndex: 1, explanation: "〜をください is used when making a purchase or ordering food." }
    ],
    "Lesson 4": [
        { question: "Get up, wake up", options: ["おきます", "ねます", "はたらきます", "やすみます"], correctIndex: 0, explanation: "おきます means to wake up or get up." },
        { question: "Sleep, go to bed", options: ["おきます", "ねます", "べんきょうします", "おわります"], correctIndex: 1, explanation: "ねます means to sleep." },
        { question: "Work", options: ["はたらきます", "やすみます", "べんきょうします", "おわります"], correctIndex: 0, explanation: "はたらきます means to work." },
        { question: "Take a rest, take a holiday", options: ["はたらきます", "やすみます", "おきます", "ねます"], correctIndex: 1, explanation: "やすみます means to rest or take a day off." },
        { question: "Study", options: ["おわります", "べんきょうします", "はたらきます", "おきます"], correctIndex: 1, explanation: "べんきょうします means to study." },
        { question: "Finish", options: ["やすみます", "べんきょうします", "おわります", "ねます"], correctIndex: 2, explanation: "おわります means to finish." },
        { question: "Department store", options: ["デパート", "ぎんこう", "ゆうびんきょく", "としょかん"], correctIndex: 0, explanation: "デパート means department store." },
        { question: "Bank", options: ["デパート", "ぎんこう", "としょかん", "びじゅつかん"], correctIndex: 1, explanation: "ぎんこう means bank." },
        { question: "Post office", options: ["ゆうびんきょく", "ぎんこう", "としょかん", "デパート"], correctIndex: 0, explanation: "ゆうびんきょく means post office." },
        { question: "Library", options: ["びじゅつかん", "としょかん", "ゆうびんきょく", "ぎんこう"], correctIndex: 1, explanation: "としょかん means library." },
        { question: "Art museum", options: ["デパート", "としょかん", "びじゅつかん", "ゆうびんきょく"], correctIndex: 2, explanation: "びじゅつかん means art museum." },
        { question: "Now", options: ["いま", "あさ", "ひる", "ばん"], correctIndex: 0, explanation: "いま means now." },
        { question: "—o'clock", options: ["〜ふん", "〜じ", "〜はん", "〜にち"], correctIndex: 1, explanation: "〜じ is the counter for hours (o'clock)." },
        { question: "—minute", options: ["〜じ", "〜ふん / 〜ぷん", "〜はん", "〜がつ"], correctIndex: 1, explanation: "〜ふん or 〜ぷん is the counter for minutes." },
        { question: "Half", options: ["いま", "〜じ", "はん", "なんじ"], correctIndex: 2, explanation: "はん is used for half-past the hour (e.g., いちじはん = 1:30)." },
        { question: "What time", options: ["なんぷん", "なんじ", "いつ", "なんようび"], correctIndex: 1, explanation: "なんじ means what time." },
        { question: "What minute", options: ["なんじ", "なんぷん", "いつ", "なんようび"], correctIndex: 1, explanation: "なんぷん means what minute." },
        { question: "a.m., morning", options: ["ごご", "ごぜん", "あさ", "ひる"], correctIndex: 1, explanation: "ごぜん means a.m." },
        { question: "p.m., afternoon", options: ["ごぜん", "ごご", "ばん", "よる"], correctIndex: 1, explanation: "ごご means p.m." },
        { question: "Morning", options: ["あさ", "ひる", "ばん", "よる"], correctIndex: 0, explanation: "あさ means morning." },
        { question: "Daytime, noon", options: ["あさ", "ひる", "ばん", "よる"], correctIndex: 1, explanation: "ひる means daytime or noon." },
        { question: "Night, evening", options: ["あさ", "ひる", "ばん / よる", "いま"], correctIndex: 2, explanation: "ばん or よる means night or evening." },
        { question: "The day before yesterday", options: ["おととい", "きのう", "きょう", "あした"], correctIndex: 0, explanation: "おととい means the day before yesterday." },
        { question: "Yesterday", options: ["おととい", "きのう", "きょう", "あした"], correctIndex: 1, explanation: "きのう means yesterday." },
        { question: "Today", options: ["きのう", "きょう", "あした", "あさって"], correctIndex: 1, explanation: "きょう means today." },
        { question: "Tomorrow", options: ["きのう", "きょう", "あした", "あさって"], correctIndex: 2, explanation: "あした means tomorrow." },
        { question: "The day after tomorrow", options: ["きのう", "きょう", "あした", "あさって"], correctIndex: 3, explanation: "あさって means the day after tomorrow." },
        { question: "This morning", options: ["けさ", "こんばん", "まいあさ", "まいばん"], correctIndex: 0, explanation: "けさ means this morning." },
        { question: "This evening, tonight", options: ["けさ", "こんばん", "まいあさ", "まいばん"], correctIndex: 1, explanation: "こんばん means this evening or tonight." },
        { question: "Rest, a holiday, a day off", options: ["やすみ", "ひるやすみ", "まいあさ", "まいにち"], correctIndex: 0, explanation: "やすみ means a rest or a holiday." },
        { question: "Lunchtime", options: ["やすみ", "ひるやすみ", "まいにち", "ばん"], correctIndex: 1, explanation: "ひるやすみ means lunch break." },
        { question: "Every morning", options: ["まいあさ", "まいばん", "まいにち", "けさ"], correctIndex: 0, explanation: "まいあさ means every morning." },
        { question: "Every night", options: ["まいあさ", "まいばん", "まいにち", "こんばん"], correctIndex: 1, explanation: "まいばん means every night." },
        { question: "Every day", options: ["まいあさ", "まいばん", "まいにち", "きょう"], correctIndex: 2, explanation: "まいにち means every day." },
        { question: "Monday", options: ["げつようび", "かようび", "すいようび", "もくようび"], correctIndex: 0, explanation: "げつようび means Monday." },
        { question: "Tuesday", options: ["げつようび", "かようび", "すいようび", "もくようび"], correctIndex: 1, explanation: "かようび means Tuesday." },
        { question: "Wednesday", options: ["げつようび", "かようび", "すいようび", "もくようび"], correctIndex: 2, explanation: "すいようび means Wednesday." },
        { question: "Thursday", options: ["げつようび", "かようび", "すいようび", "もくようび"], correctIndex: 3, explanation: "もくようび means Thursday." },
        { question: "Friday", options: ["きんようび", "どようび", "にちようび", "なんようび"], correctIndex: 0, explanation: "きんようび means Friday." },
        { question: "Saturday", options: ["きんようび", "どようび", "にちようび", "なんようび"], correctIndex: 1, explanation: "どようび means Saturday." },
        { question: "Sunday", options: ["きんようび", "どようび", "にちようび", "なんようび"], correctIndex: 2, explanation: "にちようび means Sunday." },
        { question: "What day of the week", options: ["きんようび", "どようび", "にちようび", "なんようび"], correctIndex: 3, explanation: "なんようび means what day of the week." },
        { question: "Number", options: ["ばんごう", "なんばん", "〜から", "〜まで"], correctIndex: 0, explanation: "ばんごう means number." },
        { question: "What number", options: ["ばんごう", "なんばん", "〜から", "〜まで"], correctIndex: 1, explanation: "なんばん means what number." },
        { question: "From ~", options: ["〜まで", "〜から", "〜と", "〜じ"], correctIndex: 1, explanation: "〜から means from (time or place)." },
        { question: "Up to ~, until ~", options: ["〜から", "〜まで", "〜と", "〜じ"], correctIndex: 1, explanation: "〜まで means until or up to." },
        { question: "And (used to connect nouns)", options: ["〜から", "〜まで", "〜と", "〜じ"], correctIndex: 2, explanation: "〜と is used to link two nouns (e.g., ほん と じしょ)." },
        { question: "That's tough, isn't it? (expressing sympathy)", options: ["えーと", "たいへんですね", "おねがいします", "かしこまりました"], correctIndex: 1, explanation: "たいへんですね is used to express sympathy for someone's hardship." },
        { question: "Well, let me see", options: ["えーと", "たいへんですね", "おねがいします", "かしこまりました"], correctIndex: 0, explanation: "えーと is a filler word used when thinking." },
        { question: "Please (asking for a favor)", options: ["えーと", "たいへんですね", "おねがいします", "かしこまりました"], correctIndex: 2, explanation: "おねがいします means please." },
        { question: "Certainly (sir, madam)", options: ["えーと", "たいへんですね", "おねがいします", "かしこまりました"], correctIndex: 3, explanation: "かしこまりました is a very polite way to say 'I understand' or 'Certainly'." }
    ],
    "Lesson 5": [
        { question: "Go", options: ["いきます", "きます", "かえります", "おきます"], correctIndex: 0, explanation: "いきます means to go." },
        { question: "Come", options: ["いきます", "きます", "かえります", "ねます"], correctIndex: 1, explanation: "きます means to come." },
        { question: "Go home, return", options: ["いきます", "きます", "かえります", "はたらきます"], correctIndex: 2, explanation: "かえります means to go home or return." },
        { question: "School", options: ["がっこう", "スーパー", "えき", "ひこうき"], correctIndex: 0, explanation: "がっこう means school." },
        { question: "Supermarket", options: ["がっこう", "スーパー", "えき", "ふね"], correctIndex: 1, explanation: "スーパー means supermarket." },
        { question: "Station", options: ["がっこう", "スーパー", "えき", "でんしゃ"], correctIndex: 2, explanation: "えき means train station." },
        { question: "Airplane", options: ["ひこうき", "ふね", "でんしゃ", "ちかてつ"], correctIndex: 0, explanation: "ひこうき means airplane." },
        { question: "Ship", options: ["ひこうき", "ふね", "しんかんせん", "バス"], correctIndex: 1, explanation: "ふね means ship or boat." },
        { question: "Electric train", options: ["タクシー", "じてんしゃ", "でんしゃ", "ちかてつ"], correctIndex: 2, explanation: "でんしゃ means electric train." },
        { question: "Subway, underground", options: ["でんしゃ", "ちかてつ", "しんかんせん", "バス"], correctIndex: 1, explanation: "ちかてつ means subway." },
        { question: "Bullet train", options: ["でんしゃ", "ちかてつ", "しんかんせん", "タクシー"], correctIndex: 2, explanation: "しんかんせん means the Shinkansen (bullet train)." },
        { question: "Bus", options: ["でんしゃ", "ちかてつ", "しんかんせん", "バス"], correctIndex: 3, explanation: "バス means bus." },
        { question: "Taxi", options: ["じてんしゃ", "タクシー", "ひこうき", "ふね"], correctIndex: 1, explanation: "タクシー means taxi." },
        { question: "Bicycle", options: ["バス", "タクシー", "じてんしゃ", "でんしゃ"], correctIndex: 2, explanation: "じてんしゃ means bicycle." },
        { question: "On foot", options: ["ひとりで", "あるいて", "じてんしゃ", "ちかてつ"], correctIndex: 1, explanation: "あるいて means on foot / walking." },
        { question: "Person, people", options: ["ひと", "ともだち", "かれ", "かのじょ"], correctIndex: 0, explanation: "ひと means person or people." },
        { question: "Friend", options: ["ひと", "ともだち", "かれ", "かのじょ"], correctIndex: 1, explanation: "ともだち means friend." },
        { question: "He, boyfriend", options: ["ひと", "ともだち", "かれ", "かのじょ"], correctIndex: 2, explanation: "かれ means he or boyfriend." },
        { question: "She, girlfriend", options: ["ともだち", "かぞく", "かれ", "かのじょ"], correctIndex: 3, explanation: "かのじょ means she or girlfriend." },
        { question: "Family", options: ["ひと", "ともだち", "かぞく", "かれ"], correctIndex: 2, explanation: "かぞく means family." },
        { question: "Alone, by oneself", options: ["ひとりで", "あるいて", "かぞく", "ともだち"], correctIndex: 0, explanation: "ひとりで means by oneself or alone." },
        { question: "Last week", options: ["せんしゅう", "こんしゅう", "らいしゅう", "せんげつ"], correctIndex: 0, explanation: "せんしゅう means last week." },
        { question: "This week", options: ["せんしゅう", "こんしゅう", "らいしゅう", "こんげつ"], correctIndex: 1, explanation: "こんしゅう means this week." },
        { question: "Next week", options: ["せんしゅう", "こんしゅう", "らいしゅう", "らいげつ"], correctIndex: 2, explanation: "らいしゅう means next week." },
        { question: "Last month", options: ["せんげつ", "こんげつ", "らいげつ", "きょねん"], correctIndex: 0, explanation: "せんげつ means last month." },
        { question: "This month", options: ["せんげつ", "こんげつ", "らいげつ", "ことし"], correctIndex: 1, explanation: "こんげつ means this month." },
        { question: "Next month", options: ["せんげつ", "こんげつ", "らいげつ", "らいねん"], correctIndex: 2, explanation: "らいげつ means next month." },
        { question: "Last year", options: ["きょねん", "ことし", "らいねん", "せんげつ"], correctIndex: 0, explanation: "きょねん means last year." },
        { question: "This year", options: ["きょねん", "ことし", "らいねん", "こんげつ"], correctIndex: 1, explanation: "ことし means this year." },
        { question: "Next year", options: ["きょねん", "ことし", "らいねん", "らいげつ"], correctIndex: 2, explanation: "らいねん means next year." },
        { question: "—th month of the year", options: ["〜がつ", "なんがつ", "〜にち", "なんにち"], correctIndex: 0, explanation: "〜がつ is the counter for months of the year (e.g., いちがつ is January)." },
        { question: "What month", options: ["〜がつ", "なんがつ", "〜にち", "なんにち"], correctIndex: 1, explanation: "なんがつ means what month." },
        { question: "1st day of the month", options: ["ついたち", "ふつか", "みっか", "よっか"], correctIndex: 0, explanation: "ついたち is the 1st." },
        { question: "2nd day of the month / two days", options: ["ついたち", "ふつか", "みっか", "よっか"], correctIndex: 1, explanation: "ふつか is the 2nd." },
        { question: "3rd day of the month / three days", options: ["ついたち", "ふつか", "みっか", "よっか"], correctIndex: 2, explanation: "みっか is the 3rd." },
        { question: "4th day of the month / four days", options: ["ついたち", "ふつか", "みっか", "よっか"], correctIndex: 3, explanation: "よっか is the 4th." },
        { question: "5th day of the month / five days", options: ["いつか", "むいか", "なのか", "ようか"], correctIndex: 0, explanation: "いつか is the 5th." },
        { question: "6th day of the month / six days", options: ["いつか", "むいか", "なのか", "ようか"], correctIndex: 1, explanation: "むいか is the 6th." },
        { question: "7th day of the month / seven days", options: ["いつか", "むいか", "なのか", "ようか"], correctIndex: 2, explanation: "なのか is the 7th." },
        { question: "8th day of the month / eight days", options: ["いつか", "むいか", "なのか", "ようか"], correctIndex: 3, explanation: "ようか is the 8th." },
        { question: "9th day of the month / nine days", options: ["ここのか", "とおか", "じゅうよっか", "はつか"], correctIndex: 0, explanation: "ここのか is the 9th." },
        { question: "10th day of the month / ten days", options: ["ここのか", "とおか", "じゅうよっか", "はつか"], correctIndex: 1, explanation: "とおか is the 10th." },
        { question: "14th day of the month / fourteen days", options: ["ここのか", "とおか", "じゅうよっか", "はつか"], correctIndex: 2, explanation: "じゅうよっか is the 14th." },
        { question: "20th day of the month / twenty days", options: ["ここのか", "とおか", "じゅうよっか", "はつか"], correctIndex: 3, explanation: "はつか is the 20th." },
        { question: "24th day of the month / twenty-four days", options: ["はつか", "にじゅうよっか", "〜にち", "なんにち"], correctIndex: 1, explanation: "にじゅうよっか is the 24th." },
        { question: "—th day of the month, —days", options: ["〜がつ", "なんがつ", "〜にち", "なんにち"], correctIndex: 2, explanation: "〜にち is the counter for days." },
        { question: "Which day of the month, how many days", options: ["〜がつ", "なんがつ", "〜にち", "なんにち"], correctIndex: 3, explanation: "なんにち means what day of the month." },
        { question: "When", options: ["いつ", "どこ", "だれ", "なん"], correctIndex: 0, explanation: "いつ means when." },
        { question: "Birthday", options: ["たんじょうび", "ふつう", "きゅうこう", "とっきゅう"], correctIndex: 0, explanation: "たんじょうび means birthday." },
        { question: "Local (train)", options: ["たんじょうび", "ふつう", "きゅうこう", "とっきゅう"], correctIndex: 1, explanation: "ふつう means a local train (stops at every station)." },
        { question: "Rapid (train)", options: ["たんじょうび", "ふつう", "きゅうこう", "とっきゅう"], correctIndex: 2, explanation: "きゅうこう means a rapid train." },
        { question: "Express (train)", options: ["たんじょうび", "ふつう", "きゅうこう", "とっきゅう"], correctIndex: 3, explanation: "とっきゅう means an express train." },
        { question: "Next", options: ["つぎの", "ふつう", "きゅうこう", "とっきゅう"], correctIndex: 0, explanation: "つぎの means next (e.g., つぎの えき = next station)." },
        { question: "You're welcome / Don't mention it", options: ["どういたしまして", "〜ばんせん", "つぎの", "たんじょうび"], correctIndex: 0, explanation: "どういたしまして is used to say you're welcome." },
        { question: "Platform ~", options: ["どういたしまして", "〜ばんせん", "つぎの", "ふつう"], correctIndex: 1, explanation: "〜ばんせん indicates the platform number at a train station." }
    ]
};