// --- DATA STRUCTURE: Minna No Nihongo Vocabulary ---
const minnaNoNihongoData = {
    "Lesson 1": [
        { question: "I, Me", options: ["わたし", "あなた", "あのひと", "だれ"], correctIndex: 0, explanation: "わたし means I or me." },
        { question: "We", options: ["わたし", "あなた", "わたしたち", "みなさん"], correctIndex: 2, explanation: "わたしたち means we." },
        { question: "You", options: ["わたし", "あなた", "あのひと", "みなさん"], correctIndex: 1, explanation: "あなた means you." },
        { question: "That person, he, she", options: ["だれ", "どなた", "あなた", "あのひと"], correctIndex: 3, explanation: "あのひと means that person (he/she)." },
        { question: "That person, he, she (polite equivalent)", options: ["あのかた", "あのひと", "あなた", "みなさん"], correctIndex: 0, explanation: "あのかた is the polite equivalent of あのひと." },
        { question: "Ladies and gentlemen, all of you", options: ["みなさん", "わたしたち", "あのひと", "あなた"], correctIndex: 0, explanation: "みなさん means everyone or all of you." },
        { question: "Mr., Ms. (title of respect)", options: ["〜ちゃん", "〜じん", "〜さん", "〜さい"], correctIndex: 2, explanation: "〜さん is a title of respect added to a name." },
        { question: "Suffix often added to a child's name", options: ["〜さん", "〜ちゃん", "〜じん", "〜さい"], correctIndex: 1, explanation: "〜ちゃん is used affectionately for children." },
        { question: "Suffix meaning a national of a country", options: ["〜さん", "〜ちゃん", "〜じん", "〜さい"], correctIndex: 2, explanation: "〜じん indicates nationality (e.g., アメリカじん)." },
        { question: "Teacher, Instructor", options: ["がくせい", "せんせい", "いしゃ", "きょうし"], correctIndex: 1, explanation: "せんせい means teacher." },
        { question: "Teacher, Instructor (referring to one's own profession)", options: ["がくせい", "せんせい", "いしゃ", "きょうし"], correctIndex: 3, explanation: "きょうし is used when talking about your own job as a teacher." },
        { question: "Student", options: ["せんせい", "ぎんこういん", "がくせい", "エンジニア"], correctIndex: 2, explanation: "がくせい means student." },
        { question: "Company employee", options: ["かいしゃいん", "しゃいん", "いしゃ", "けんきゅうしゃ"], correctIndex: 0, explanation: "かいしゃいん means company employee." },
        { question: "Employee of ~ company", options: ["かいしゃいん", "しゃいん", "ぎんこういん", "せんせい"], correctIndex: 1, explanation: "しゃいん is used with a company name (e.g., IMCのしゃいん)." },
        { question: "Bank employee", options: ["いしゃ", "ぎんこういん", "かいしゃいん", "せんせい"], correctIndex: 1, explanation: "ぎんこういん means bank employee." },
        { question: "Medical doctor", options: ["エンジニア", "けんきゅうしゃ", "がくせい", "いしゃ"], correctIndex: 3, explanation: "いしゃ means medical doctor." },
        { question: "Researcher, scholar", options: ["けんきゅうしゃ", "いしゃ", "せんせい", "しゃいん"], correctIndex: 0, explanation: "けんきゅうしゃ means researcher." },
        { question: "Engineer", options: ["エンジニア", "いしゃ", "ぎんこういん", "がくせい"], correctIndex: 0, explanation: "エンジニア is the katakana word for engineer." },
        { question: "University", options: ["びょういん", "だいがく", "ぎんこう", "かいしゃ"], correctIndex: 1, explanation: "だいがく means university." },
        { question: "Hospital", options: ["だいがく", "びょういん", "ぎんこう", "かいしゃ"], correctIndex: 1, explanation: "びょういん means hospital." },
        { question: "Electricity, light", options: ["だいがく", "びょういん", "でんき", "かいしゃ"], correctIndex: 2, explanation: "でんき means electricity or light." },
        { question: "Who", options: ["だれ", "なに", "どこ", "いつ"], correctIndex: 0, explanation: "だれ means who." },
        { question: "Who (polite equivalent)", options: ["どなた", "だれ", "なに", "どこ"], correctIndex: 0, explanation: "どなた is the polite equivalent of だれ." },
        { question: "—years old", options: ["〜さん", "〜ちゃん", "〜じん", "〜さい"], correctIndex: 3, explanation: "〜さい is the counter for age." },
        { question: "How old", options: ["だれ", "どなた", "なんさい", "いつ"], correctIndex: 2, explanation: "なんさい means how old." },
        { question: "How old (polite equivalent)", options: ["なんさい", "おいくつ", "だれ", "どなた"], correctIndex: 1, explanation: "おいくつ is the polite equivalent of なんさい." },
        { question: "Yes", options: ["いいえ", "はい", "そう", "ちがいます"], correctIndex: 1, explanation: "はい means yes." },
        { question: "No", options: ["はい", "いいえ", "そう", "ちがいます"], correctIndex: 1, explanation: "いいえ means no." },
        { question: "How do you do? (meeting for the first time)", options: ["どうぞよろしく", "はじめまして", "しつれいですが", "おなまえは？"], correctIndex: 1, explanation: "はじめまして is used when meeting someone for the first time." },
        { question: "I'm from ~ (country)", options: ["〜からきました", "〜じん", "〜さん", "〜さい"], correctIndex: 0, explanation: "〜からきました means 'I came from...' or 'I am from...'." },
        { question: "Pleased to meet you", options: ["はじめまして", "どうぞよろしく", "しつれいですが", "おなまえは？"], correctIndex: 1, explanation: "どうぞよろしく (or どうぞよろしくおねがいします) means pleased to meet you." },
        { question: "Excuse me, but", options: ["はじめまして", "どうぞよろしく", "しつれいですが", "おなまえは？"], correctIndex: 2, explanation: "しつれいですが is used when asking for personal information like a name." },
        { question: "May I have your name?", options: ["はじめまして", "どうぞよろしく", "しつれいですが", "おなまえは？"], correctIndex: 3, explanation: "おなまえは？ means 'What is your name?'." },
        { question: "This is Mr./Ms. ~", options: ["こちらは〜さんです", "〜からきました", "どうぞよろしく", "はじめまして"], correctIndex: 0, explanation: "こちらは〜さんです is used when introducing someone else." }
    ],
    "Lesson 2": [
        { question: "This (thing here)", options: ["それ", "あれ", "これ", "どれ"], correctIndex: 2, explanation: "これ refers to a thing near the speaker." },
        { question: "That (thing near the listener)", options: ["これ", "それ", "あれ", "どれ"], correctIndex: 1, explanation: "それ refers to a thing near the listener." },
        { question: "That (thing over there)", options: ["これ", "それ", "あれ", "どれ"], correctIndex: 2, explanation: "あれ refers to a thing far from both speaker and listener." },
        { question: "Which one", options: ["これ", "それ", "あれ", "どれ"], correctIndex: 3, explanation: "どれ means which one." },
        { question: "This ~ (noun)", options: ["この", "その", "あの", "どの"], correctIndex: 0, explanation: "この must be followed by a noun (e.g., この ほん)." },
        { question: "That ~ (noun) near the listener", options: ["この", "その", "あの", "どの"], correctIndex: 1, explanation: "その must be followed by a noun." },
        { question: "That ~ (noun) over there", options: ["この", "その", "あの", "どの"], correctIndex: 2, explanation: "あの must be followed by a noun." },
        { question: "Which ~ (noun)", options: ["この", "その", "あの", "どの"], correctIndex: 3, explanation: "どの must be followed by a noun." },
        { question: "Book", options: ["じしょ", "ほん", "ざっし", "しんぶん"], correctIndex: 1, explanation: "ほん means book." },
        { question: "Dictionary", options: ["ほん", "ざっし", "じしょ", "てちょう"], correctIndex: 2, explanation: "じしょ means dictionary." },
        { question: "Magazine", options: ["しんぶん", "ざっし", "ノート", "ほん"], correctIndex: 1, explanation: "ざっし means magazine." },
        { question: "Newspaper", options: ["しんぶん", "ざっし", "てちょう", "じしょ"], correctIndex: 0, explanation: "しんぶん means newspaper." },
        { question: "Notebook", options: ["てちょう", "ノート", "めいし", "カード"], correctIndex: 1, explanation: "ノート is a katakana word for notebook." },
        { question: "Pocket notebook", options: ["ノート", "ほん", "てちょう", "めいし"], correctIndex: 2, explanation: "てちょう means a small pocket notebook." },
        { question: "Business card", options: ["カード", "めいし", "えんぴつ", "かぎ"], correctIndex: 1, explanation: "めいし means business card." },
        { question: "Card", options: ["カード", "めいし", "てちょう", "ノート"], correctIndex: 0, explanation: "カード means card (like a credit card or key card)." },
        { question: "Telephone card", options: ["カード", "テレホンカード", "めいし", "ノート"], correctIndex: 1, explanation: "テレホンカード means telephone card." },
        { question: "Pencil", options: ["ボールペン", "シャープペンシル", "えんぴつ", "かさ"], correctIndex: 2, explanation: "えんぴつ means pencil." },
        { question: "Ballpoint pen", options: ["ボールペン", "シャープペンシル", "えんぴつ", "かぎ"], correctIndex: 0, explanation: "ボールペン is a katakana word for ballpoint pen." },
        { question: "Mechanical pencil", options: ["ボールペン", "シャープペンシル", "えんぴつ", "ノート"], correctIndex: 1, explanation: "シャープペンシル is a mechanical pencil." },
        { question: "Key", options: ["かぎ", "とけい", "かさ", "かばん"], correctIndex: 0, explanation: "かぎ means key." },
        { question: "Watch, clock", options: ["とけい", "かぎ", "かさ", "くつ"], correctIndex: 0, explanation: "とけい means watch or clock." },
        { question: "Umbrella", options: ["かぎ", "とけい", "かさ", "かばん"], correctIndex: 2, explanation: "かさ means umbrella." },
        { question: "Bag, briefcase", options: ["かさ", "かばん", "つくえ", "いす"], correctIndex: 1, explanation: "かばん means bag or briefcase." },
        { question: "Cassette tape", options: ["テープ", "ラジオ", "テレビ", "カメラ"], correctIndex: 0, explanation: "テープ means tape or cassette tape." },
        { question: "CD, Compact Disc", options: ["テープ", "CD", "テレビ", "カメラ"], correctIndex: 1, explanation: "CD means compact disc." },
        { question: "Television", options: ["ラジオ", "カメラ", "テレビ", "コンピューター"], correctIndex: 2, explanation: "テレビ means television." },
        { question: "Radio", options: ["ラジオ", "カメラ", "テレビ", "コンピューター"], correctIndex: 0, explanation: "ラジオ means radio." },
        { question: "Camera", options: ["ラジオ", "カメラ", "テレビ", "コンピューター"], correctIndex: 1, explanation: "カメラ means camera." },
        { question: "Computer", options: ["ラジオ", "カメラ", "テレビ", "コンピューター"], correctIndex: 3, explanation: "コンピューター means computer." },
        { question: "Automobile, car", options: ["じどうしゃ", "テレビ", "ラジオ", "カメラ"], correctIndex: 0, explanation: "じどうしゃ means car. くるま is also commonly used." },
        { question: "Desk", options: ["いす", "つくえ", "テレビ", "カメラ"], correctIndex: 1, explanation: "つくえ means desk." },
        { question: "Chair", options: ["つくえ", "いす", "かばん", "かさ"], correctIndex: 1, explanation: "いす means chair." },
        { question: "Chocolate", options: ["チョコレート", "コーヒー", "テレビ", "ラジオ"], correctIndex: 0, explanation: "チョコレート means chocolate." },
        { question: "Coffee", options: ["チョコレート", "コーヒー", "ノート", "カメラ"], correctIndex: 1, explanation: "コーヒー means coffee." },
        { question: "English language", options: ["えいご", "にほんご", "〜ご", "なん"], correctIndex: 0, explanation: "えいご means the English language." },
        { question: "Japanese language", options: ["えいご", "にほんご", "〜ご", "なん"], correctIndex: 1, explanation: "にほんご means the Japanese language." },
        { question: "〜 language", options: ["えいご", "にほんご", "〜ご", "なん"], correctIndex: 2, explanation: "〜ご is the suffix for languages (e.g., フランスご)." },
        { question: "What", options: ["だれ", "どこ", "いつ", "なん"], correctIndex: 3, explanation: "なん (or なに) means what." },
        { question: "Yes, it is. / That's right.", options: ["そうです", "ちがいます", "そうですか", "どうぞ"], correctIndex: 0, explanation: "そうです is used to agree or confirm." },
        { question: "No, it isn't. / You are wrong.", options: ["そうです", "ちがいます", "そうですか", "どうぞ"], correctIndex: 1, explanation: "ちがいます literally means 'it is different' but is used to say 'no, that's incorrect'." },
        { question: "I see. / Is that so?", options: ["そうです", "ちがいます", "そうですか", "どうぞ"], correctIndex: 2, explanation: "そうですか is used to show you understand new information." },
        { question: "Well... (hesitation)", options: ["あのう", "どうぞ", "どうも", "そうです"], correctIndex: 0, explanation: "あのう is a filler word used when hesitating or getting someone's attention politely." },
        { question: "It's nothing. / It's a token of my gratitude.", options: ["ほんのきもちです", "どうぞ", "どうも", "そうですか"], correctIndex: 0, explanation: "ほんのきもちです is often said when giving a small gift." },
        { question: "Please. / Here you are.", options: ["どうぞ", "どうも", "あのう", "そうです"], correctIndex: 0, explanation: "どうぞ is used when offering something to someone." },
        { question: "Well / Thanks", options: ["どうも", "どうぞ", "あのう", "そうです"], correctIndex: 0, explanation: "どうも is a casual way to say thanks, or used to emphasize a greeting." },
        { question: "Thank you very much.", options: ["どうぞよろしく", "どうもありがとうございます", "そうですか", "ちがいます"], correctIndex: 1, explanation: "どうもありがとうございます is the standard polite way to say thank you." },
        { question: "I hope for your kind assistance from now on.", options: ["こちらこそよろしく", "これからおせわになります", "ほんのきもちです", "そうですか"], correctIndex: 1, explanation: "これからおせわになります is a formal greeting used when starting a new relationship." },
        { question: "I am pleased to meet you too. / The pleasure is mine.", options: ["これからおせわになります", "こちらこそよろしく", "ほんのきもちです", "どうも"], correctIndex: 1, explanation: "こちらこそよろしく is the polite reply to どうぞよろしく." }
    ],
    "Lesson 3": [
        { question: "Here, this place", options: ["そこ", "あそこ", "ここ", "どこ"], correctIndex: 2, explanation: "ここ means here." },
        { question: "There, that place near you", options: ["ここ", "そこ", "あそこ", "どこ"], correctIndex: 1, explanation: "そこ means there." },
        { question: "That place over there", options: ["ここ", "そこ", "あそこ", "どこ"], correctIndex: 2, explanation: "あそこ means over there." },
        { question: "Where, what place", options: ["ここ", "そこ", "あそこ", "どこ"], correctIndex: 3, explanation: "どこ means where." },
        { question: "This way, this place (polite equivalent of ここ)", options: ["そちら", "こちら", "あちら", "どちら"], correctIndex: 1, explanation: "こちら is the polite form of ここ." },
        { question: "That way, that place (polite equivalent of そこ)", options: ["こちら", "そちら", "あちら", "どちら"], correctIndex: 1, explanation: "そちら is the polite form of そこ." },
        { question: "That way, that place over there (polite equivalent of あそこ)", options: ["こちら", "そちら", "あちら", "どちら"], correctIndex: 2, explanation: "あちら is the polite form of あそこ." },
        { question: "Which way, where (polite equivalent of どこ)", options: ["こちら", "そちら", "あちら", "どちら"], correctIndex: 3, explanation: "どちら is the polite form of どこ." },
        { question: "Classroom", options: ["しょくどう", "きょうしつ", "じむしょ", "へや"], correctIndex: 1, explanation: "きょうしつ means classroom." },
        { question: "Dining hall, canteen", options: ["きょうしつ", "じむしょ", "しょくどう", "かいぎしつ"], correctIndex: 2, explanation: "しょくどう means dining hall or canteen." },
        { question: "Office", options: ["じむしょ", "きょうしつ", "しょくどう", "うけつけ"], correctIndex: 0, explanation: "じむしょ means office." },
        { question: "Conference room, assembly room", options: ["しょくどう", "じむしょ", "かいぎしつ", "ロビー"], correctIndex: 2, explanation: "かいぎしつ means conference room." },
        { question: "Reception desk", options: ["うけつけ", "ロビー", "へや", "トイレ"], correctIndex: 0, explanation: "うけつけ means reception desk." },
        { question: "Lobby", options: ["うけつけ", "ロビー", "へや", "かいだん"], correctIndex: 1, explanation: "ロビー is a katakana word for lobby." },
        { question: "Room", options: ["へや", "トイレ", "かいだん", "うち"], correctIndex: 0, explanation: "へや means room." },
        { question: "Toilet, restroom", options: ["へや", "おてあらい", "かいだん", "エレベーター"], correctIndex: 1, explanation: "おてあらい (or トイレ) means restroom/toilet." },
        { question: "Staircase", options: ["トイレ", "エレベーター", "かいだん", "エスカレーター"], correctIndex: 2, explanation: "かいだん means staircase or stairs." },
        { question: "Elevator, lift", options: ["かいだん", "エスカレーター", "エレベーター", "うち"], correctIndex: 2, explanation: "エレベーター is elevator." },
        { question: "Escalator", options: ["かいだん", "エレベーター", "エスカレーター", "へや"], correctIndex: 2, explanation: "エスカレーター is escalator." },
        { question: "Country", options: ["かいしゃ", "うち", "くに", "でんわ"], correctIndex: 2, explanation: "くに (or おくに) means country." },
        { question: "Company", options: ["くに", "かいしゃ", "うち", "くつ"], correctIndex: 1, explanation: "かいしゃ means company." },
        { question: "House, home", options: ["うち", "くに", "かいしゃ", "でんわ"], correctIndex: 0, explanation: "うち means house or home." },
        { question: "Telephone, telephone call", options: ["くつ", "でんわ", "ネクタイ", "ワイン"], correctIndex: 1, explanation: "でんわ means telephone." },
        { question: "Shoes", options: ["ネクタイ", "ワイン", "くつ", "たばこ"], correctIndex: 2, explanation: "くつ means shoes." },
        { question: "Necktie", options: ["くつ", "ネクタイ", "ワイン", "うりば"], correctIndex: 1, explanation: "ネクタイ means necktie." },
        { question: "Wine", options: ["ネクタイ", "ワイン", "たばこ", "ちか"], correctIndex: 1, explanation: "ワイン means wine." },
        { question: "Tobacco, cigarette", options: ["ワイン", "たばこ", "うりば", "ちか"], correctIndex: 1, explanation: "たばこ means tobacco or cigarette." },
        { question: "Department, counter (in a store)", options: ["ちか", "うりば", "かい", "えん"], correctIndex: 1, explanation: "うりば means selling area or counter." },
        { question: "Basement", options: ["ちか", "うりば", "かい", "えん"], correctIndex: 0, explanation: "ちか means basement or underground." },
        { question: "—th floor", options: ["〜えん", "〜かい / 〜がい", "いくら", "なんがい"], correctIndex: 1, explanation: "〜かい (or 〜がい for 3rd floor) is the counter for floors." },
        { question: "What floor", options: ["いくら", "なんがい", "ひゃく", "せん"], correctIndex: 1, explanation: "なんがい means what floor." },
        { question: "—yen", options: ["〜かい", "〜えん", "いくら", "まん"], correctIndex: 1, explanation: "〜えん is the counter for Japanese yen." },
        { question: "How much", options: ["なんがい", "いくら", "ひゃく", "せん"], correctIndex: 1, explanation: "いくら means how much (price)." },
        { question: "Hundred", options: ["ひゃく", "せん", "まん", "えん"], correctIndex: 0, explanation: "ひゃく means one hundred." },
        { question: "Thousand", options: ["ひゃく", "せん", "まん", "いくら"], correctIndex: 1, explanation: "せん means one thousand." },
        { question: "Ten thousand", options: ["ひゃく", "せん", "まん", "えん"], correctIndex: 2, explanation: "まん means ten thousand." },
        { question: "Excuse me", options: ["じゃ", "すみません", "ください", "でございます"], correctIndex: 1, explanation: "すみません is used to apologize or get someone's attention." },
        { question: "Polite equivalent of です", options: ["すみません", "〜でございます", "〜をみせてください", "じゃ"], correctIndex: 1, explanation: "〜でございます is a very polite way to say 'is/are'." },
        { question: "Please show me ~", options: ["じゃ", "〜をみせてください", "〜をください", "すみません"], correctIndex: 1, explanation: "〜をみせてください is used when asking a shop clerk to show you an item." },
        { question: "Well, then, in that case", options: ["じゃ", "すみません", "〜でございます", "どうぞ"], correctIndex: 0, explanation: "じゃ is a conversational way to say 'well then'." },
        { question: "Give me ~, please", options: ["〜をみせてください", "〜をください", "じゃ", "すみません"], correctIndex: 1, explanation: "〜をください is used when making a purchase or ordering food." }
    ],
    "Lesson 4": [
        { question: "Get up, wake up", options: ["おきます", "ねます", "はたらきます", "やすみます"], correctIndex: 0, explanation: "おきます means to wake up or get up." },
        { question: "Sleep, go to bed", options: ["おきます", "ねます", "べんきょうします", "おわります"], correctIndex: 1, explanation: "ねます means to sleep." },
        { question: "Work", options: ["はたらきます", "やすみます", "べんきょうします", "おわります"], correctIndex: 0, explanation: "はたらきます means to work." },
        { question: "Take a rest, take a holiday", options: ["はたらきます", "やすみます", "おきます", "ねます"], correctIndex: 1, explanation: "やすみます means to rest or take a day off." },
        { question: "Study", options: ["おわります", "べんきょうします", "はたらきます", "おきます"], correctIndex: 1, explanation: "べんきょうします means to study." },
        { question: "Finish", options: ["やすみます", "べんきょうします", "おわります", "ねます"], correctIndex: 2, explanation: "おわります means to finish." },
        { question: "Department store", options: ["デパート", "ぎんこう", "ゆうびんきょく", "としょかん"], correctIndex: 0, explanation: "デパート means department store." },
        { question: "Bank", options: ["デパート", "ぎんこう", "としょかん", "びじゅつかん"], correctIndex: 1, explanation: "ぎんこう means bank." },
        { question: "Post office", options: ["ゆうびんきょく", "ぎんこう", "としょかん", "デパート"], correctIndex: 0, explanation: "ゆうびんきょく means post office." },
        { question: "Library", options: ["びじゅつかん", "としょかん", "ゆうびんきょく", "ぎんこう"], correctIndex: 1, explanation: "としょかん means library." },
        { question: "Art museum", options: ["デパート", "としょかん", "びじゅつかん", "ゆうびんきょく"], correctIndex: 2, explanation: "びじゅつかん means art museum." },
        { question: "Now", options: ["いま", "あさ", "ひる", "ばん"], correctIndex: 0, explanation: "いま means now." },
        { question: "—o'clock", options: ["〜ふん", "〜じ", "〜はん", "〜にち"], correctIndex: 1, explanation: "〜じ is the counter for hours (o'clock)." },
        { question: "—minute", options: ["〜じ", "〜ふん / 〜ぷん", "〜はん", "〜がつ"], correctIndex: 1, explanation: "〜ふん or 〜ぷん is the counter for minutes." },
        { question: "Half", options: ["いま", "〜じ", "はん", "なんじ"], correctIndex: 2, explanation: "はん is used for half-past the hour (e.g., いちじはん = 1:30)." },
        { question: "What time", options: ["なんぷん", "なんじ", "いつ", "なんようび"], correctIndex: 1, explanation: "なんじ means what time." },
        { question: "What minute", options: ["なんじ", "なんぷん", "いつ", "なんようび"], correctIndex: 1, explanation: "なんぷん means what minute." },
        { question: "a.m., morning", options: ["ごご", "ごぜん", "あさ", "ひる"], correctIndex: 1, explanation: "ごぜん means a.m." },
        { question: "p.m., afternoon", options: ["ごぜん", "ごご", "ばん", "よる"], correctIndex: 1, explanation: "ごご means p.m." },
        { question: "Morning", options: ["あさ", "ひる", "ばん", "よる"], correctIndex: 0, explanation: "あさ means morning." },
        { question: "Daytime, noon", options: ["あさ", "ひる", "ばん", "よる"], correctIndex: 1, explanation: "ひる means daytime or noon." },
        { question: "Night, evening", options: ["あさ", "ひる", "ばん / よる", "いま"], correctIndex: 2, explanation: "ばん or よる means night or evening." },
        { question: "The day before yesterday", options: ["おととい", "きのう", "きょう", "あした"], correctIndex: 0, explanation: "おととい means the day before yesterday." },
        { question: "Yesterday", options: ["おととい", "きのう", "きょう", "あした"], correctIndex: 1, explanation: "きのう means yesterday." },
        { question: "Today", options: ["きのう", "きょう", "あした", "あさって"], correctIndex: 1, explanation: "きょう means today." },
        { question: "Tomorrow", options: ["きのう", "きょう", "あした", "あさって"], correctIndex: 2, explanation: "あした means tomorrow." },
        { question: "The day after tomorrow", options: ["きのう", "きょう", "あした", "あさって"], correctIndex: 3, explanation: "あさって means the day after tomorrow." },
        { question: "This morning", options: ["けさ", "こんばん", "まいあさ", "まいばん"], correctIndex: 0, explanation: "けさ means this morning." },
        { question: "This evening, tonight", options: ["けさ", "こんばん", "まいあさ", "まいばん"], correctIndex: 1, explanation: "こんばん means this evening or tonight." },
        { question: "Rest, a holiday, a day off", options: ["やすみ", "ひるやすみ", "まいあさ", "まいにち"], correctIndex: 0, explanation: "やすみ means a rest or a holiday." },
        { question: "Lunchtime", options: ["やすみ", "ひるやすみ", "まいにち", "ばん"], correctIndex: 1, explanation: "ひるやすみ means lunch break." },
        { question: "Every morning", options: ["まいあさ", "まいばん", "まいにち", "けさ"], correctIndex: 0, explanation: "まいあさ means every morning." },
        { question: "Every night", options: ["まいあさ", "まいばん", "まいにち", "こんばん"], correctIndex: 1, explanation: "まいばん means every night." },
        { question: "Every day", options: ["まいあさ", "まいばん", "まいにち", "きょう"], correctIndex: 2, explanation: "まいにち means every day." },
        { question: "Monday", options: ["げつようび", "かようび", "すいようび", "もくようび"], correctIndex: 0, explanation: "げつようび means Monday." },
        { question: "Tuesday", options: ["げつようび", "かようび", "すいようび", "もくようび"], correctIndex: 1, explanation: "かようび means Tuesday." },
        { question: "Wednesday", options: ["げつようび", "かようび", "すいようび", "もくようび"], correctIndex: 2, explanation: "すいようび means Wednesday." },
        { question: "Thursday", options: ["げつようび", "かようび", "すいようび", "もくようび"], correctIndex: 3, explanation: "もくようび means Thursday." },
        { question: "Friday", options: ["きんようび", "どようび", "にちようび", "なんようび"], correctIndex: 0, explanation: "きんようび means Friday." },
        { question: "Saturday", options: ["きんようび", "どようび", "にちようび", "なんようび"], correctIndex: 1, explanation: "どようび means Saturday." },
        { question: "Sunday", options: ["きんようび", "どようび", "にちようび", "なんようび"], correctIndex: 2, explanation: "にちようび means Sunday." },
        { question: "What day of the week", options: ["きんようび", "どようび", "にちようび", "なんようび"], correctIndex: 3, explanation: "なんようび means what day of the week." },
        { question: "Number", options: ["ばんごう", "なんばん", "〜から", "〜まで"], correctIndex: 0, explanation: "ばんごう means number." },
        { question: "What number", options: ["ばんごう", "なんばん", "〜から", "〜まで"], correctIndex: 1, explanation: "なんばん means what number." },
        { question: "From ~", options: ["〜まで", "〜から", "〜と", "〜じ"], correctIndex: 1, explanation: "〜から means from (time or place)." },
        { question: "Up to ~, until ~", options: ["〜から", "〜まで", "〜と", "〜じ"], correctIndex: 1, explanation: "〜まで means until or up to." },
        { question: "And (used to connect nouns)", options: ["〜から", "〜まで", "〜と", "〜じ"], correctIndex: 2, explanation: "〜と is used to link two nouns (e.g., ほん と じしょ)." },
        { question: "That's tough, isn't it? (expressing sympathy)", options: ["えーと", "たいへんですね", "おねがいします", "かしこまりました"], correctIndex: 1, explanation: "たいへんですね is used to express sympathy for someone's hardship." },
        { question: "Well, let me see", options: ["えーと", "たいへんですね", "おねがいします", "かしこまりました"], correctIndex: 0, explanation: "えーと is a filler word used when thinking." },
        { question: "Please (asking for a favor)", options: ["えーと", "たいへんですね", "おねがいします", "かしこまりました"], correctIndex: 2, explanation: "おねがいします means please." },
        { question: "Certainly (sir, madam)", options: ["えーと", "たいへんですね", "おねがいします", "かしこまりました"], correctIndex: 3, explanation: "かしこまりました is a very polite way to say 'I understand' or 'Certainly'." }
    ],
    "Lesson 5": [
        { question: "Go", options: ["いきます", "きます", "かえります", "おきます"], correctIndex: 0, explanation: "いきます means to go." },
        { question: "Come", options: ["いきます", "きます", "かえります", "ねます"], correctIndex: 1, explanation: "きます means to come." },
        { question: "Go home, return", options: ["いきます", "きます", "かえります", "はたらきます"], correctIndex: 2, explanation: "かえります means to go home or return." },
        { question: "School", options: ["がっこう", "スーパー", "えき", "ひこうき"], correctIndex: 0, explanation: "がっこう means school." },
        { question: "Supermarket", options: ["がっこう", "スーパー", "えき", "ふね"], correctIndex: 1, explanation: "スーパー means supermarket." },
        { question: "Station", options: ["がっこう", "スーパー", "えき", "でんしゃ"], correctIndex: 2, explanation: "えき means train station." },
        { question: "Airplane", options: ["ひこうき", "ふね", "でんしゃ", "ちかてつ"], correctIndex: 0, explanation: "ひこうき means airplane." },
        { question: "Ship", options: ["ひこうき", "ふね", "しんかんせん", "バス"], correctIndex: 1, explanation: "ふね means ship or boat." },
        { question: "Electric train", options: ["タクシー", "じてんしゃ", "でんしゃ", "ちかてつ"], correctIndex: 2, explanation: "でんしゃ means electric train." },
        { question: "Subway, underground", options: ["でんしゃ", "ちかてつ", "しんかんせん", "バス"], correctIndex: 1, explanation: "ちかてつ means subway." },
        { question: "Bullet train", options: ["でんしゃ", "ちかてつ", "しんかんせん", "タクシー"], correctIndex: 2, explanation: "しんかんせん means the Shinkansen (bullet train)." },
        { question: "Bus", options: ["でんしゃ", "ちかてつ", "しんかんせん", "バス"], correctIndex: 3, explanation: "バス means bus." },
        { question: "Taxi", options: ["じてんしゃ", "タクシー", "ひこうき", "ふね"], correctIndex: 1, explanation: "タクシー means taxi." },
        { question: "Bicycle", options: ["バス", "タクシー", "じてんしゃ", "でんしゃ"], correctIndex: 2, explanation: "じてんしゃ means bicycle." },
        { question: "On foot", options: ["ひとりで", "あるいて", "じてんしゃ", "ちかてつ"], correctIndex: 1, explanation: "あるいて means on foot / walking." },
        { question: "Person, people", options: ["ひと", "ともだち", "かれ", "かのじょ"], correctIndex: 0, explanation: "ひと means person or people." },
        { question: "Friend", options: ["ひと", "ともだち", "かれ", "かのじょ"], correctIndex: 1, explanation: "ともだち means friend." },
        { question: "He, boyfriend", options: ["ひと", "ともだち", "かれ", "かのじょ"], correctIndex: 2, explanation: "かれ means he or boyfriend." },
        { question: "She, girlfriend", options: ["ともだち", "かぞく", "かれ", "かのじょ"], correctIndex: 3, explanation: "かのじょ means she or girlfriend." },
        { question: "Family", options: ["ひと", "ともだち", "かぞく", "かれ"], correctIndex: 2, explanation: "かぞく means family." },
        { question: "Alone, by oneself", options: ["ひとりで", "あるいて", "かぞく", "ともだち"], correctIndex: 0, explanation: "ひとりで means by oneself or alone." },
        { question: "Last week", options: ["せんしゅう", "こんしゅう", "らいしゅう", "せんげつ"], correctIndex: 0, explanation: "せんしゅう means last week." },
        { question: "This week", options: ["せんしゅう", "こんしゅう", "らいしゅう", "こんげつ"], correctIndex: 1, explanation: "こんしゅう means this week." },
        { question: "Next week", options: ["せんしゅう", "こんしゅう", "らいしゅう", "らいげつ"], correctIndex: 2, explanation: "らいしゅう means next week." },
        { question: "Last month", options: ["せんげつ", "こんげつ", "らいげつ", "きょねん"], correctIndex: 0, explanation: "せんげつ means last month." },
        { question: "This month", options: ["せんげつ", "こんげつ", "らいげつ", "ことし"], correctIndex: 1, explanation: "こんげつ means this month." },
        { question: "Next month", options: ["せんげつ", "こんげつ", "らいげつ", "らいねん"], correctIndex: 2, explanation: "らいげつ means next month." },
        { question: "Last year", options: ["きょねん", "ことし", "らいねん", "せんげつ"], correctIndex: 0, explanation: "きょねん means last year." },
        { question: "This year", options: ["きょねん", "ことし", "らいねん", "こんげつ"], correctIndex: 1, explanation: "ことし means this year." },
        { question: "Next year", options: ["きょねん", "ことし", "らいねん", "らいげつ"], correctIndex: 2, explanation: "らいねん means next year." },
        { question: "—th month of the year", options: ["〜がつ", "なんがつ", "〜にち", "なんにち"], correctIndex: 0, explanation: "〜がつ is the counter for months of the year (e.g., いちがつ is January)." },
        { question: "What month", options: ["〜がつ", "なんがつ", "〜にち", "なんにち"], correctIndex: 1, explanation: "なんがつ means what month." },
        { question: "1st day of the month", options: ["ついたち", "ふつか", "みっか", "よっか"], correctIndex: 0, explanation: "ついたち is the 1st." },
        { question: "2nd day of the month / two days", options: ["ついたち", "ふつか", "みっか", "よっか"], correctIndex: 1, explanation: "ふつか is the 2nd." },
        { question: "3rd day of the month / three days", options: ["ついたち", "ふつか", "みっか", "よっか"], correctIndex: 2, explanation: "みっか is the 3rd." },
        { question: "4th day of the month / four days", options: ["ついたち", "ふつか", "みっか", "よっか"], correctIndex: 3, explanation: "よっか is the 4th." },
        { question: "5th day of the month / five days", options: ["いつか", "むいか", "なのか", "ようか"], correctIndex: 0, explanation: "いつか is the 5th." },
        { question: "6th day of the month / six days", options: ["いつか", "むいか", "なのか", "ようか"], correctIndex: 1, explanation: "むいか is the 6th." },
        { question: "7th day of the month / seven days", options: ["いつか", "むいか", "なのか", "ようか"], correctIndex: 2, explanation: "なのか is the 7th." },
        { question: "8th day of the month / eight days", options: ["いつか", "むいか", "なのか", "ようか"], correctIndex: 3, explanation: "ようか is the 8th." },
        { question: "9th day of the month / nine days", options: ["ここのか", "とおか", "じゅうよっか", "はつか"], correctIndex: 0, explanation: "ここのか is the 9th." },
        { question: "10th day of the month / ten days", options: ["ここのか", "とおか", "じゅうよっか", "はつか"], correctIndex: 1, explanation: "とおか is the 10th." },
        { question: "14th day of the month / fourteen days", options: ["ここのか", "とおか", "じゅうよっか", "はつか"], correctIndex: 2, explanation: "じゅうよっか is the 14th." },
        { question: "20th day of the month / twenty days", options: ["ここのか", "とおか", "じゅうよっか", "はつか"], correctIndex: 3, explanation: "はつか is the 20th." },
        { question: "24th day of the month / twenty-four days", options: ["はつか", "にじゅうよっか", "〜にち", "なんにち"], correctIndex: 1, explanation: "にじゅうよっか is the 24th." },
        { question: "—th day of the month, —days", options: ["〜がつ", "なんがつ", "〜にち", "なんにち"], correctIndex: 2, explanation: "〜にち is the counter for days." },
        { question: "Which day of the month, how many days", options: ["〜がつ", "なんがつ", "〜にち", "なんにち"], correctIndex: 3, explanation: "なんにち means what day of the month." },
        { question: "When", options: ["いつ", "どこ", "だれ", "なん"], correctIndex: 0, explanation: "いつ means when." },
        { question: "Birthday", options: ["たんじょうび", "ふつう", "きゅうこう", "とっきゅう"], correctIndex: 0, explanation: "たんじょうび means birthday." },
        { question: "Local (train)", options: ["たんじょうび", "ふつう", "きゅうこう", "とっきゅう"], correctIndex: 1, explanation: "ふつう means a local train (stops at every station)." },
        { question: "Rapid (train)", options: ["たんじょうび", "ふつう", "きゅうこう", "とっきゅう"], correctIndex: 2, explanation: "きゅうこう means a rapid train." },
        { question: "Express (train)", options: ["たんじょうび", "ふつう", "きゅうこう", "とっきゅう"], correctIndex: 3, explanation: "とっきゅう means an express train." },
        { question: "Next", options: ["つぎの", "ふつう", "きゅうこう", "とっきゅう"], correctIndex: 0, explanation: "つぎの means next (e.g., つぎの えき = next station)." },
        { question: "You're welcome / Don't mention it", options: ["どういたしまして", "〜ばんせん", "つぎの", "たんじょうび"], correctIndex: 0, explanation: "どういたしまして is used to say you're welcome." },
        { question: "Platform ~", options: ["どういたしまして", "〜ばんせん", "つぎの", "ふつう"], correctIndex: 1, explanation: "〜ばんせん indicates the platform number at a train station." }
    ],
    "Lesson 6": [
        { question: "Eat", options: ["たべます", "のみます", "すいます", "みます"], correctIndex: 0, explanation: "たべます means to eat." },
        { question: "Drink", options: ["たべます", "のみます", "ききます", "よみます"], correctIndex: 1, explanation: "のみます means to drink." },
        { question: "Smoke (a cigarette)", options: ["かきます", "かいます", "すいます", "とります"], correctIndex: 2, explanation: "すいます means to smoke (e.g., たばこを すいます)." },
        { question: "See, look at, watch", options: ["みます", "ききます", "よみます", "かきます"], correctIndex: 0, explanation: "みます means to see, look at, or watch." },
        { question: "Hear, listen", options: ["みます", "ききます", "よみます", "かきます"], correctIndex: 1, explanation: "ききます means to hear or listen." },
        { question: "Read", options: ["みます", "ききます", "よみます", "かきます"], correctIndex: 2, explanation: "よみます means to read." },
        { question: "Write, draw, paint", options: ["みます", "ききます", "よみます", "かきます"], correctIndex: 3, explanation: "かきます means to write, draw, or paint." },
        { question: "Buy", options: ["かいます", "とります", "します", "あいます"], correctIndex: 0, explanation: "かいます means to buy." },
        { question: "Take (a photograph)", options: ["かいます", "とります", "します", "あいます"], correctIndex: 1, explanation: "とります means to take (a photo). (e.g., しゃしんを とります)." },
        { question: "Do", options: ["かいます", "とります", "します", "あいます"], correctIndex: 2, explanation: "します means to do." },
        { question: "Meet (a friend)", options: ["かいます", "とります", "します", "あいます"], correctIndex: 3, explanation: "あいます means to meet (e.g., ともだちに あいます)." },
        { question: "A meal, cooked rice", options: ["ごはん", "あさごはん", "ひるごはん", "ばんごはん"], correctIndex: 0, explanation: "ごはん means cooked rice or a meal." },
        { question: "Breakfast", options: ["ごはん", "あさごはん", "ひるごはん", "ばんごはん"], correctIndex: 1, explanation: "あさごはん means breakfast." },
        { question: "Lunch", options: ["ごはん", "あさごはん", "ひるごはん", "ばんごはん"], correctIndex: 2, explanation: "ひるごはん means lunch." },
        { question: "Supper, dinner", options: ["ごはん", "あさごはん", "ひるごはん", "ばんごはん"], correctIndex: 3, explanation: "ばんごはん means supper or dinner." },
        { question: "Bread", options: ["パン", "たまご", "にく", "さかな"], correctIndex: 0, explanation: "パン is a katakana word for bread." },
        { question: "Egg", options: ["パン", "たまご", "にく", "さかな"], correctIndex: 1, explanation: "たまご means egg." },
        { question: "Meat", options: ["パン", "たまご", "にく", "さかな"], correctIndex: 2, explanation: "にく means meat." },
        { question: "Fish", options: ["やさい", "くだもの", "さかな", "みず"], correctIndex: 2, explanation: "さかな means fish." },
        { question: "Vegetable", options: ["やさい", "くだもの", "さかな", "みず"], correctIndex: 0, explanation: "やさい means vegetable." },
        { question: "Fruit", options: ["やさい", "くだもの", "おちゃ", "こうちゃ"], correctIndex: 1, explanation: "くだもの means fruit." },
        { question: "Water", options: ["みず", "おちゃ", "こうちゃ", "ぎゅうにゅう"], correctIndex: 0, explanation: "みず means water." },
        { question: "Tea, green tea", options: ["みず", "おちゃ", "こうちゃ", "ジュース"], correctIndex: 1, explanation: "おちゃ means tea (usually green tea)." },
        { question: "Black tea", options: ["おちゃ", "こうちゃ", "ぎゅうにゅう", "ビール"], correctIndex: 1, explanation: "こうちゃ means black tea." },
        { question: "Milk", options: ["おちゃ", "こうちゃ", "ぎゅうにゅう", "おさけ"], correctIndex: 2, explanation: "ぎゅうにゅう (or ミルク) means milk." },
        { question: "Juice", options: ["ジュース", "ビール", "おさけ", "おちゃ"], correctIndex: 0, explanation: "ジュース is a katakana word for juice." },
        { question: "Beer", options: ["ジュース", "ビール", "おさけ", "こうちゃ"], correctIndex: 1, explanation: "ビール is a katakana word for beer." },
        { question: "Alcohol, Japanese rice wine", options: ["ジュース", "ビール", "おさけ", "みず"], correctIndex: 2, explanation: "おさけ means alcohol or sake." },
        { question: "Video tape, video deck", options: ["ビデオ", "えいが", "てがみ", "しゃしん"], correctIndex: 0, explanation: "ビデオ means video." },
        { question: "Movie", options: ["ビデオ", "えいが", "てがみ", "しゃしん"], correctIndex: 1, explanation: "えいが means movie." },
        { question: "CD, Compact Disc", options: ["CD", "てがみ", "レポート", "しゃしん"], correctIndex: 0, explanation: "CD means compact disc." },
        { question: "Letter", options: ["えいが", "てがみ", "レポート", "みせ"], correctIndex: 1, explanation: "てがみ means letter." },
        { question: "Report", options: ["えいが", "てがみ", "レポート", "しゃしん"], correctIndex: 2, explanation: "レポート is a katakana word for report." },
        { question: "Photograph", options: ["てがみ", "レポート", "しゃしん", "みせ"], correctIndex: 2, explanation: "しゃしん means photograph." },
        { question: "Store, shop", options: ["みせ", "レストラン", "にわ", "えいが"], correctIndex: 0, explanation: "みせ means store or shop." },
        { question: "Restaurant", options: ["みせ", "レストラン", "にわ", "しゅくだい"], correctIndex: 1, explanation: "レストラン is a katakana word for restaurant." },
        { question: "Garden", options: ["みせ", "レストラン", "にわ", "テニス"], correctIndex: 2, explanation: "にわ means garden." },
        { question: "Homework", options: ["しゅくだい", "テニス", "サッカー", "おはなみ"], correctIndex: 0, explanation: "しゅくだい means homework (e.g., しゅくだいを します)." },
        { question: "Tennis", options: ["しゅくだい", "テニス", "サッカー", "おはなみ"], correctIndex: 1, explanation: "テニス is tennis." },
        { question: "Soccer, football", options: ["しゅくだい", "テニス", "サッカー", "おはなみ"], correctIndex: 2, explanation: "サッカー is soccer." },
        { question: "Cherry-blossom viewing", options: ["しゅくだい", "テニス", "サッカー", "おはなみ"], correctIndex: 3, explanation: "おはなみ means cherry-blossom viewing." },
        { question: "What", options: ["なに", "いっしょに", "ちょっと", "いつも"], correctIndex: 0, explanation: "なに means what." },
        { question: "Together", options: ["なに", "いっしょに", "ちょっと", "いつも"], correctIndex: 1, explanation: "いっしょに means together." },
        { question: "A little while, a little bit", options: ["なに", "いっしょに", "ちょっと", "いつも"], correctIndex: 2, explanation: "ちょっと means a little bit or for a short while." },
        { question: "Always, usually", options: ["なに", "いっしょに", "ちょっと", "いつも"], correctIndex: 3, explanation: "いつも means always." },
        { question: "Sometimes", options: ["ときどき", "それから", "ええ", "いいですね"], correctIndex: 0, explanation: "ときどき means sometimes." },
        { question: "After that, and then", options: ["ときどき", "それから", "ええ", "いいですね"], correctIndex: 1, explanation: "それから means after that, or and then." },
        { question: "Yes (informal)", options: ["ときどき", "それから", "ええ", "いいですね"], correctIndex: 2, explanation: "ええ is an informal agreement similar to はい." },
        { question: "That's good", options: ["ときどき", "それから", "ええ", "いいですね"], correctIndex: 3, explanation: "いいですね means 'That's good' or 'Sounds good'." },
        { question: "I see / I understand", options: ["わかりました", "なんですか", "じゃ、また", "いいですね"], correctIndex: 0, explanation: "わかりました means 'I understand'." },
        { question: "Yes? / What is it?", options: ["わかりました", "なんですか", "じゃ、また", "ええ"], correctIndex: 1, explanation: "なんですか is used to ask what something is or to respond when called." },
        { question: "See you [tomorrow]", options: ["わかりました", "なんですか", "じゃ、また", "ええ"], correctIndex: 2, explanation: "じゃ、また（あした） means 'See you (tomorrow)'." }
    ],
    "Lesson 7": [
        { question: "Cut, slice", options: ["きります", "おくります", "あげます", "もらいます"], correctIndex: 0, explanation: "きります means to cut." },
        { question: "Send", options: ["きります", "おくります", "あげます", "もらいます"], correctIndex: 1, explanation: "おくります means to send (e.g., にもつを おくります)." },
        { question: "Give", options: ["きります", "おくります", "あげます", "もらいます"], correctIndex: 2, explanation: "あげます means to give." },
        { question: "Receive", options: ["きります", "おくります", "あげます", "もらいます"], correctIndex: 3, explanation: "もらいます means to receive." },
        { question: "Lend", options: ["かします", "かります", "おしえます", "ならいます"], correctIndex: 0, explanation: "かします means to lend." },
        { question: "Borrow", options: ["かします", "かります", "おしえます", "ならいます"], correctIndex: 1, explanation: "かります means to borrow." },
        { question: "Teach", options: ["かします", "かります", "おしえます", "ならいます"], correctIndex: 2, explanation: "おしえます means to teach." },
        { question: "Learn", options: ["かします", "かります", "おしえます", "ならいます"], correctIndex: 3, explanation: "ならいます means to learn." },
        { question: "Make (a telephone call)", options: ["かけます", "きります", "おくります", "あげます"], correctIndex: 0, explanation: "かけます means to make a call (e.g., でんわを かけます)." },
        { question: "Hand, arm", options: ["て", "はし", "スプーン", "ナイフ"], correctIndex: 0, explanation: "て means hand or arm." },
        { question: "Chopsticks", options: ["て", "はし", "スプーン", "ナイフ"], correctIndex: 1, explanation: "はし means chopsticks." },
        { question: "Spoon", options: ["て", "はし", "スプーン", "ナイフ"], correctIndex: 2, explanation: "スプーン is a katakana word for spoon." },
        { question: "Knife", options: ["スプーン", "ナイフ", "フォーク", "はさみ"], correctIndex: 1, explanation: "ナイフ is a katakana word for knife." },
        { question: "Fork", options: ["スプーン", "ナイフ", "フォーク", "はさみ"], correctIndex: 2, explanation: "フォーク is a katakana word for fork." },
        { question: "Scissors", options: ["スプーン", "ナイフ", "フォーク", "はさみ"], correctIndex: 3, explanation: "はさみ means scissors." },
        { question: "Fax", options: ["ファクス", "ワープロ", "パソコン", "パンチ"], correctIndex: 0, explanation: "ファクス is fax." },
        { question: "Word processor", options: ["ファクス", "ワープロ", "パソコン", "パンチ"], correctIndex: 1, explanation: "ワープロ is word processor." },
        { question: "Personal computer", options: ["ファクス", "ワープロ", "パソコン", "パンチ"], correctIndex: 2, explanation: "パソコン is personal computer." },
        { question: "Punch", options: ["パソコン", "パンチ", "ホッチキス", "セロテープ"], correctIndex: 1, explanation: "パンチ is hole punch." },
        { question: "Stapler", options: ["パソコン", "パンチ", "ホッチキス", "セロテープ"], correctIndex: 2, explanation: "ホッチキス is stapler." },
        { question: "Scotch tape, clear adhesive tape", options: ["パンチ", "ホッチキス", "セロテープ", "けしゴム"], correctIndex: 2, explanation: "セロテープ is scotch tape." },
        { question: "Eraser", options: ["ホッチキス", "セロテープ", "けしゴム", "かみ"], correctIndex: 2, explanation: "けしゴム means eraser." },
        { question: "Paper", options: ["ホッチキス", "セロテープ", "けしゴム", "かみ"], correctIndex: 3, explanation: "かみ means paper." },
        { question: "Flower, blossom", options: ["はな", "シャツ", "プレゼント", "にもつ"], correctIndex: 0, explanation: "はな means flower." },
        { question: "Shirt", options: ["はな", "シャツ", "プレゼント", "にもつ"], correctIndex: 1, explanation: "シャツ means shirt." },
        { question: "Present, gift", options: ["はな", "シャツ", "プレゼント", "にもつ"], correctIndex: 2, explanation: "プレゼント means present or gift." },
        { question: "Baggage, parcel", options: ["シャツ", "プレゼント", "にもつ", "おかね"], correctIndex: 2, explanation: "にもつ means baggage or parcel." },
        { question: "Money", options: ["シャツ", "プレゼント", "にもつ", "おかね"], correctIndex: 3, explanation: "おかね means money." },
        { question: "Ticket", options: ["きっぷ", "ちち", "はは", "おとうさん"], correctIndex: 0, explanation: "きっぷ means ticket (for train/bus)." },
        { question: "My father", options: ["きっぷ", "ちち", "はは", "おとうさん"], correctIndex: 1, explanation: "ちち is used when referring to your own father." },
        { question: "My mother", options: ["ちち", "はは", "おとうさん", "おかあさん"], correctIndex: 1, explanation: "はは is used when referring to your own mother." },
        { question: "Someone else's father", options: ["ちち", "はは", "おとうさん", "おかあさん"], correctIndex: 2, explanation: "おとうさん is used when talking about someone else's father." },
        { question: "Someone else's mother", options: ["ちち", "はは", "おとうさん", "おかあさん"], correctIndex: 3, explanation: "おかあさん is used when talking about someone else's mother." },
        { question: "Already", options: ["もう", "まだ", "これから", "すてきですね"], correctIndex: 0, explanation: "もう means already (e.g., もう たべました)." },
        { question: "Not yet", options: ["もう", "まだ", "これから", "すてきですね"], correctIndex: 1, explanation: "まだ means not yet." },
        { question: "From now on, soon", options: ["もう", "まだ", "これから", "すてきですね"], correctIndex: 2, explanation: "これから means from now on or soon." },
        { question: "What a nice [~]!", options: ["もう", "まだ", "これから", "すてきですね"], correctIndex: 3, explanation: "すてきですね means 'What a nice...' or 'How lovely!'." },
        { question: "Excuse me / Anybody home?", options: ["ごめんください", "いらっしゃい", "どうぞ おあがりください", "しつれいします"], correctIndex: 0, explanation: "ごめんください is used by a visitor when entering someone's home." },
        { question: "How nice of you to come / Welcome", options: ["ごめんください", "いらっしゃい", "どうぞ おあがりください", "しつれいします"], correctIndex: 1, explanation: "いらっしゃい is used to welcome a guest." },
        { question: "Please come in", options: ["ごめんください", "いらっしゃい", "どうぞ おあがりください", "しつれいします"], correctIndex: 2, explanation: "どうぞ おあがりください is said to invite a guest to step up into the house." },
        { question: "May I? / Excuse me (on entering)", options: ["ごめんください", "いらっしゃい", "どうぞ おあがりください", "しつれいします"], correctIndex: 3, explanation: "しつれいします is said when entering someone's house or room." },
        { question: "Won't you have [~]? / How about [~]?", options: ["いかがですか", "いただきます", "りょこう", "おみやげ"], correctIndex: 0, explanation: "いかがですか is used when offering something to someone." },
        { question: "Thank you (said before eating/drinking)", options: ["いかがですか", "いただきます", "りょこう", "おみやげ"], correctIndex: 1, explanation: "いただきます is said right before starting a meal." },
        { question: "Trip, tour", options: ["いかがですか", "いただきます", "りょこう", "おみやげ"], correctIndex: 2, explanation: "りょこう means trip or tour." },
        { question: "Souvenir, present", options: ["いかがですか", "いただきます", "りょこう", "おみやげ"], correctIndex: 3, explanation: "おみやげ means souvenir or gift from a trip." },
        { question: "Oh! / What!", options: ["えっ", "もう", "まだ", "これから"], correctIndex: 0, explanation: "えっ is an expression of surprise." }
    ],
    "Lesson 8": [
        { question: "Handsome", options: ["ハンサム（な）", "きれい（な）", "しずか（な）", "にぎやか（な）"], correctIndex: 0, explanation: "ハンサム is a na-adjective for handsome." },
        { question: "Beautiful, clean", options: ["ハンサム（な）", "きれい（な）", "しずか（な）", "にぎやか（な）"], correctIndex: 1, explanation: "きれい is a na-adjective for beautiful or clean." },
        { question: "Quiet", options: ["ハンサム（な）", "きれい（な）", "しずか（な）", "にぎやか（な）"], correctIndex: 2, explanation: "しずか is a na-adjective for quiet." },
        { question: "Lively", options: ["ハンサム（な）", "きれい（な）", "しずか（な）", "にぎやか（な）"], correctIndex: 3, explanation: "にぎやか is a na-adjective for lively." },
        { question: "Famous", options: ["ゆうめい（な）", "しんせつ（な）", "げんき（な）", "ひま（な）"], correctIndex: 0, explanation: "ゆうめい is a na-adjective for famous." },
        { question: "Kind", options: ["ゆうめい（な）", "しんせつ（な）", "げんき（な）", "ひま（な）"], correctIndex: 1, explanation: "しんせつ is a na-adjective for kind." },
        { question: "Healthy, sound, cheerful", options: ["ゆうめい（な）", "しんせつ（な）", "げんき（な）", "ひま（な）"], correctIndex: 2, explanation: "げんき is a na-adjective for healthy or cheerful." },
        { question: "Free (time)", options: ["ゆうめい（な）", "しんせつ（な）", "げんき（な）", "ひま（な）"], correctIndex: 3, explanation: "ひま is a na-adjective for free time." },
        { question: "Convenient", options: ["べんり（な）", "すてき（な）", "おおきい", "ちいさい"], correctIndex: 0, explanation: "べんり is a na-adjective for convenient." },
        { question: "Fine, nice, wonderful", options: ["べんり（な）", "すてき（な）", "おおきい", "ちいさい"], correctIndex: 1, explanation: "すてき is a na-adjective for wonderful or nice." },
        { question: "Big, large", options: ["べんり（な）", "すてき（な）", "おおきい", "ちいさい"], correctIndex: 2, explanation: "おおきい is an i-adjective for big." },
        { question: "Small, little", options: ["べんり（な）", "すてき（な）", "おおきい", "ちいさい"], correctIndex: 3, explanation: "ちいさい is an i-adjective for small." },
        { question: "New", options: ["あたらしい", "ふるい", "いい", "わるい"], correctIndex: 0, explanation: "あたらしい is an i-adjective for new." },
        { question: "Old (not for age)", options: ["あたらしい", "ふるい", "いい", "わるい"], correctIndex: 1, explanation: "ふるい is an i-adjective for old." },
        { question: "Good", options: ["あたらしい", "ふるい", "いい", "わるい"], correctIndex: 2, explanation: "いい (or よい) is an i-adjective for good." },
        { question: "Bad", options: ["あたらしい", "ふるい", "いい", "わるい"], correctIndex: 3, explanation: "わるい is an i-adjective for bad." },
        { question: "Hot (weather or touch)", options: ["あつい", "さむい", "つめたい", "むずかしい"], correctIndex: 0, explanation: "あつい is an i-adjective for hot." },
        { question: "Cold (weather)", options: ["あつい", "さむい", "つめたい", "むずかしい"], correctIndex: 1, explanation: "さむい is an i-adjective for cold weather." },
        { question: "Cold (to the touch)", options: ["あつい", "さむい", "つめたい", "むずかしい"], correctIndex: 2, explanation: "つめたい is an i-adjective for cold things." },
        { question: "Difficult", options: ["あつい", "さむい", "つめたい", "むずかしい"], correctIndex: 3, explanation: "むずかしい is an i-adjective for difficult." },
        { question: "Easy", options: ["やさしい", "たかい", "やすい", "ひくい"], correctIndex: 0, explanation: "やさしい is an i-adjective for easy (or kind)." },
        { question: "Expensive, high", options: ["やさしい", "たかい", "やすい", "ひくい"], correctIndex: 1, explanation: "たかい is an i-adjective for expensive or high." },
        { question: "Cheap", options: ["やさしい", "たかい", "やすい", "ひくい"], correctIndex: 2, explanation: "やすい is an i-adjective for cheap." },
        { question: "Low", options: ["やさしい", "たかい", "やすい", "ひくい"], correctIndex: 3, explanation: "ひくい is an i-adjective for low." },
        { question: "Interesting", options: ["おもしろい", "おいしい", "いそがしい", "たのしい"], correctIndex: 0, explanation: "おもしろい is an i-adjective for interesting." },
        { question: "Delicious, tasty", options: ["おもしろい", "おいしい", "いそがしい", "たのしい"], correctIndex: 1, explanation: "おいしい is an i-adjective for delicious." },
        { question: "Busy", options: ["おもしろい", "おいしい", "いそがしい", "たのしい"], correctIndex: 2, explanation: "いそがしい is an i-adjective for busy." },
        { question: "Enjoyable, fun", options: ["おもしろい", "おいしい", "いそがしい", "たのしい"], correctIndex: 3, explanation: "たのしい is an i-adjective for enjoyable or fun." },
        { question: "White", options: ["しろい", "くろい", "あかい", "あおい"], correctIndex: 0, explanation: "しろい is an i-adjective for white." },
        { question: "Black", options: ["しろい", "くろい", "あかい", "あおい"], correctIndex: 1, explanation: "くろい is an i-adjective for black." },
        { question: "Red", options: ["しろい", "くろい", "あかい", "あおい"], correctIndex: 2, explanation: "あかい is an i-adjective for red." },
        { question: "Blue", options: ["しろい", "くろい", "あかい", "あおい"], correctIndex: 3, explanation: "あおい is an i-adjective for blue." },
        { question: "Cherry blossoms", options: ["さくら", "やま", "まち", "たべもの"], correctIndex: 0, explanation: "さくら means cherry blossoms." },
        { question: "Mountain", options: ["さくら", "やま", "まち", "たべもの"], correctIndex: 1, explanation: "やま means mountain." },
        { question: "Town, city", options: ["さくら", "やま", "まち", "たべもの"], correctIndex: 2, explanation: "まち means town or city." },
        { question: "Food", options: ["さくら", "やま", "まち", "たべもの"], correctIndex: 3, explanation: "たべもの means food." },
        { question: "Place", options: ["ところ", "りょう", "レストラン", "せいかつ"], correctIndex: 0, explanation: "ところ means place." },
        { question: "Dormitory", options: ["ところ", "りょう", "レストラン", "せいかつ"], correctIndex: 1, explanation: "りょう means dormitory." },
        { question: "Life", options: ["ところ", "りょう", "レストラン", "せいかつ"], correctIndex: 3, explanation: "せいかつ means life or daily life." },
        { question: "Work, business", options: ["しごと", "どう", "どんな", "とても"], correctIndex: 0, explanation: "しごと (or おしごと) means work or business." },
        { question: "How", options: ["しごと", "どう", "どんな", "とても"], correctIndex: 1, explanation: "どう means how." },
        { question: "What kind of ~", options: ["しごと", "どう", "どんな", "とても"], correctIndex: 2, explanation: "どんな means what kind of." },
        { question: "Very", options: ["しごと", "どう", "どんな", "とても"], correctIndex: 3, explanation: "とても means very." },
        { question: "Not so (used with negatives)", options: ["あまり", "そして", "〜が、〜", "おげんきですか"], correctIndex: 0, explanation: "あまり is used with negative verbs to mean 'not so' or 'not very'." },
        { question: "And (used to connect sentences)", options: ["あまり", "そして", "〜が、〜", "おげんきですか"], correctIndex: 1, explanation: "そして means and (used to connect sentences)." },
        { question: "..., but ...", options: ["あまり", "そして", "〜が、〜", "おげんきですか"], correctIndex: 2, explanation: "〜が、〜 means '... but ...'." },
        { question: "How are you?", options: ["おげんきですか", "そうですね", "もう一杯いかがですか", "いいえ、けっこうです"], correctIndex: 0, explanation: "おげんきですか means 'How are you?'." },
        { question: "Well, let me see. (pausing)", options: ["おげんきですか", "そうですね", "もう一杯いかがですか", "いいえ、けっこうです"], correctIndex: 1, explanation: "そうですね is used to pause while thinking of an answer." },
        { question: "Won't you have another cup of [~]?", options: ["おげんきですか", "そうですね", "もう一杯いかがですか", "いいえ、けっこうです"], correctIndex: 2, explanation: "もういっぱい いかがですか means 'Would you like another cup?'." },
        { question: "No, thank you.", options: ["おげんきですか", "そうですね", "もう一杯いかがですか", "いいえ、けっこうです"], correctIndex: 3, explanation: "いいえ、けっこうです is a polite refusal." },
        { question: "It's already ~ [isn't it?]", options: ["もう〜ですね", "そろそろ失礼します", "またいらっしゃってください", "どういたしまして"], correctIndex: 0, explanation: "もう〜ですね means 'It's already... (time)'." },
        { question: "It's time I was going.", options: ["もう〜ですね", "そろそろ失礼します", "またいらっしゃってください", "どういたしまして"], correctIndex: 1, explanation: "そろそろ失礼します (そろそろしつれいします) is said when you are about to leave." },
        { question: "Please come again.", options: ["もう〜ですね", "そろそろ失礼します", "またいらっしゃってください", "どういたしまして"], correctIndex: 2, explanation: "またいらっしゃってください is a polite way to tell guests to visit again." }
    ],
 

    "N5 Kanji: Numbers": [
        { question: "一", options: ["One (いち)", "Two (に)", "Three (さん)", "Four (よん)"], correctIndex: 0, explanation: "一 is read as いち (ichi) and means One." },
        { question: "二", options: ["One (いち)", "Two (に)", "Three (さん)", "Four (よん)"], correctIndex: 1, explanation: "二 is read as に (ni) and means Two." },
        { question: "三", options: ["One (いち)", "Two (に)", "Three (さん)", "Four (よん)"], correctIndex: 2, explanation: "三 is read as さん (san) and means Three." },
        { question: "四", options: ["Five (ご)", "Two (に)", "Three (さん)", "Four (よん/し)"], correctIndex: 3, explanation: "四 is read as よん or し (yon/shi) and means Four." },
        { question: "五", options: ["Five (ご)", "Six (ろく)", "Seven (なな)", "Eight (はち)"], correctIndex: 0, explanation: "五 is read as ご (go) and means Five." },
        { question: "六", options: ["Five (ご)", "Six (ろく)", "Seven (なな)", "Eight (はち)"], correctIndex: 1, explanation: "六 is read as ろく (roku) and means Six." },
        { question: "七", options: ["Five (ご)", "Six (ろく)", "Seven (なな/しち)", "Eight (はち)"], correctIndex: 2, explanation: "七 is read as なな or しち (nana/shichi) and means Seven." },
        { question: "八", options: ["Five (ご)", "Six (ろく)", "Seven (なな)", "Eight (はち)"], correctIndex: 3, explanation: "八 is read as はち (hachi) and means Eight." },
        { question: "九", options: ["Nine (きゅう/く)", "Ten (じゅう)", "Hundred (ひゃく)", "Thousand (せん)"], correctIndex: 0, explanation: "九 is read as きゅう or く (kyuu/ku) and means Nine." },
        { question: "十", options: ["Nine (きゅう)", "Ten (じゅう)", "Hundred (ひゃく)", "Thousand (せん)"], correctIndex: 1, explanation: "十 is read as じゅう (juu) and means Ten." },
        { question: "百", options: ["Ten (じゅう)", "Hundred (ひゃく)", "Thousand (せん)", "Ten Thousand (まん)"], correctIndex: 1, explanation: "百 is read as ひゃく (hyaku) and means Hundred." },
        { question: "千", options: ["Ten (じゅう)", "Hundred (ひゃく)", "Thousand (せん)", "Ten Thousand (まん)"], correctIndex: 2, explanation: "千 is read as せん (sen) and means Thousand." },
        { question: "万", options: ["Ten (じゅう)", "Hundred (ひゃく)", "Thousand (せん)", "Ten Thousand (まん/ばん)"], correctIndex: 3, explanation: "万 is read as まん or ばん (man/ban) and means Ten Thousand." }
    ],
    
    "N5 Kanji: Days & Time": [
        { question: "日", options: ["Sun / Day (にち / ひ)", "Moon / Month (げつ / つき)", "Fire (か / ひ)", "Water (すい
};
